import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import Script from 'next/script';
import Image from 'next/image';
import {
  ArrowRight,
  CheckCircle2,
  QrCode,
  Smartphone,
  Star,
  ShieldCheck,
  Zap,
  CreditCard,
  Globe,
  Wifi,
  Users,
  FileText,
  TrendingDown,
  TrendingUp,
  Clock,
  Lock,
} from 'lucide-react';
import Footer from '@/components/shared/Footer';
import LiveQrPreview from './LiveQrPreview';
import AnimatedHeroGraphic from './AnimatedHeroGraphic';

/* ─────────────────────────────────────────────────────────────
   SEO METADATA  (Phase 4 — corrected intent + keyword)
───────────────────────────────────────────────────────────── */
export const metadata: Metadata = {
  title: 'How to Generate a QR Code for Free | NobleInvoice',
  description:
    'Learn how to generate a QR code for free in 3 steps. NobleInvoice creates payment QR codes for invoices that get you paid in 2.4 days instead of 14. Static vs dynamic explained.',
  keywords: [
    'how to generate a qr code',
    'how to generate a qr code for free',
    'create qr code free',
    'qr code generator',
    'qr code for invoice',
    'payment qr code',
    'dynamic qr code',
    'static qr code',
    'qr code generator online',
    'how can i create a qr code for free',
  ],
};

/* ─────────────────────────────────────────────────────────────
   JSON-LD  (FAQ + HowTo schema — Phase 4)
───────────────────────────────────────────────────────────── */
const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'How can I create a QR code for free?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'You can create a QR code for free in seconds using NobleInvoice — no design skills or third-party tools needed. Sign up for a free account, create an invoice, toggle on QR Payments, and your unique payment QR code is automatically generated and embedded in the invoice. Unlike most free QR generators, NobleInvoice QR codes never expire and include real-time payment tracking.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I generate a QR code for free?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'You can generate a free QR code in seconds with NobleInvoice. Sign up for a free account, create an invoice, and toggle on QR Payments. A unique, permanent QR code is automatically embedded in your invoice — no third-party generators required.',
      },
    },
    {
      '@type': 'Question',
      name: 'What is the difference between a static and dynamic QR code?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A static QR code encodes information directly into the pattern and cannot be changed after creation. A dynamic QR code stores a short URL that redirects to the destination, meaning you can update the target content after printing. NobleInvoice generates dynamic QR codes for each invoice, meaning the code remains permanently linked to that specific payment until settled.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do the QR codes expire?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. The QR codes generated by NobleInvoice never expire. They are permanently linked to that specific invoice until it is marked as paid in full.',
      },
    },
    {
      '@type': 'Question',
      name: 'What file formats can I download a QR code in?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'NobleInvoice QR codes are embedded directly into invoice PDFs and email templates. You can download or share the invoice in PDF format, which includes the QR code ready for printing or digital sharing.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I generate a QR code on my phone?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'To generate a QR code on your phone: 1. Open your browser and go to a QR code generator — NobleInvoice works on any mobile browser, no app download needed. 2. Sign in or create a free account. 3. Create an invoice and toggle QR Payments on. Your QR code is instantly generated and ready to send. On iPhone or Android, the entire process takes under 60 seconds.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is Google QR code free?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Google Chrome has a built-in QR code generator — go to any webpage, click the share icon in the address bar, and select "Create QR Code". This generates a static QR code for that URL only, with no customisation or tracking. For branded, payment-enabled QR codes that never expire, NobleInvoice includes free QR code generation built directly into your invoicing workflow at no extra cost.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does Poshmark do QR codes?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Poshmark uses QR codes specifically for prepaid shipping labels on marketplace orders. They do not offer general-purpose payment QR codes for independent sellers. If you are a seller, freelancer, or small business owner looking to invoice clients and collect payments outside of a marketplace platform, NobleInvoice generates payment QR codes that clients can pay instantly via Apple Pay or Google Pay.',
      },
    },
    {
      '@type': 'Question',
      name: 'What can I put in a QR code?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'QR codes can encode URLs, payment links, contact information (vCard), WiFi credentials, email addresses, phone numbers, and more. NobleInvoice QR codes specifically encode a secure payment link that opens Apple Pay or Google Pay on the client\'s phone.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I scan a QR code?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'To scan a QR code, open your phone\'s camera app and point it at the code. On iPhone, a notification banner appears automatically — tap it to open the link. On Android, tap the QR code icon in the camera or use Google Lens. Most modern phones scan QR codes without any additional app.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is generating a QR code free?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. NobleInvoice includes permanent, dynamic QR code generation for invoices at no extra cost on every plan, including the free tier. Unlike many generic generators that impose scan limits or expiry dates, our QR codes are unlimited and never expire.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I track QR code scans?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. NobleInvoice provides real-time tracking on each invoice. You can see when the QR code was scanned, when the client opened the payment page, and the exact moment payment was completed — all from your dashboard.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is QR code payment secure?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Extremely. NobleInvoice uses bank-level encryption and is powered by Stripe, one of the world\'s most trusted payment processors. We never store credit card data on our servers. Every QR code payment is PCI-DSS compliant.',
      },
    },
  ],
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a QR Code for Invoice Payments',
  description:
    'Generate a free payment QR code for your invoice using NobleInvoice so clients can pay instantly with Apple Pay or Google Pay.',
  totalTime: 'PT1M',
  step: [
    {
      '@type': 'HowToStep',
      position: 1,
      name: 'Create your invoice',
      text: 'Sign up for a free NobleInvoice account. Enter the client name, line items, and due date. The process takes under 60 seconds.',
    },
    {
      '@type': 'HowToStep',
      position: 2,
      name: 'Toggle QR Payments on',
      text: 'Before sending, toggle the QR Payments switch to ON. NobleInvoice automatically generates a unique, encrypted payment QR code linked to that invoice.',
    },
    {
      '@type': 'HowToStep',
      position: 3,
      name: 'Send and get paid instantly',
      text: 'Send the invoice by email. The client scans the QR code with their phone camera, approves the payment via Apple Pay or Google Pay, and you receive funds immediately.',
    },
  ],
};

/* ─────────────────────────────────────────────────────────────
   DATA CONSTANTS
───────────────────────────────────────────────────────────── */
const testimonials = [
  {
    quote:
      "I used to spend my Sunday evenings chasing payments. I switched to NobleInvoice, and the QR payments literally let clients pay me while they're walking to their cars. My average collection time went from 18 days to 3 days.",
    name: 'Ayasha Khan',
    role: 'Marketing Director, NobleMart',
    image:
      '/images/reviews/ayasha-khan-marketing-director-of-noblemart-marketplace-us-region.png',
    stars: 5,
    metric: '83% faster',
    metricLabel: 'payment collection',
  },
  {
    quote:
      "As a freelance designer, I invoice clients every week. The QR code feature means clients don't have to copy-paste bank details — they just scan and pay. My invoices are settled the same day now. Game changer.",
    name: 'Beautrice Moreau',
    role: 'Operations Manager, Eagles Media',
    image:
      '/images/reviews/beautrice-moreau-operations-manager-at-eagles-media.png',
    stars: 5,
    metric: 'Same-day',
    metricLabel: 'payment settlement',
  },
  {
    quote:
      "We manage 40+ contractor invoices per month. Before NobleInvoice, reconciling payments was a full-time job. Now every invoice has a QR code, clients pay instantly, and the dashboard auto-reconciles everything.",
    name: 'David Okafor',
    role: 'Finance Lead, Spire Builds',
    image:
      '/images/reviews/ayasha-khan-marketing-director-of-noblemart-marketplace-us-region.png',
    stars: 5,
    metric: '6 hours',
    metricLabel: 'saved weekly on reconciliation',
  },
];

const useCases = [
  {
    icon: <FileText className="w-6 h-6 text-noble-blue" />,
    title: 'Invoices & Billing',
    desc: 'Embed a payment QR code in every invoice PDF. Clients scan and pay in two taps — no bank details required.',
    highlight: true,
  },
  {
    icon: <CreditCard className="w-6 h-6 text-noble-blue" />,
    title: 'Business Cards',
    desc: 'Add your QR code to a printed or digital business card so prospects can pay a deposit or retainer on the spot.',
    highlight: false,
  },
  {
    icon: <FileText className="w-6 h-6 text-noble-blue" />,
    title: 'Restaurant Menus',
    desc: 'Link a QR code on your menu directly to your ordering page or tip collection form for contactless service.',
    highlight: false,
  },
  {
    icon: <Globe className="w-6 h-6 text-noble-blue" />,
    title: 'Marketing Flyers',
    desc: 'Drive traffic from print materials to landing pages, product listings, or booking forms instantly.',
    highlight: false,
  },
  {
    icon: <Wifi className="w-6 h-6 text-noble-blue" />,
    title: 'Event Check-in',
    desc: 'Use QR codes on event tickets for seamless entry, feedback collection, or on-site purchases.',
    highlight: false,
  },
  {
    icon: <Smartphone className="w-6 h-6 text-noble-blue" />,
    title: 'Product Packaging',
    desc: "Link product packaging QR codes to warranty registration, user manuals, or reorder pages.",
    highlight: false,
  },
  {
    icon: <Users className="w-6 h-6 text-noble-blue" />,
    title: 'Contact Sharing (vCard)',
    desc: 'Encode your full contact information into a QR code so new connections can save your details in one tap.',
    highlight: false,
  },
];

const qrSteps = [
  {
    step: '01',
    icon: <FileText className="w-6 h-6 text-noble-blue" />,
    title: 'Create Your Invoice',
    desc: 'Open NobleInvoice on any device — no download needed. Enter the client name, add your line items and due date. Takes about 45 seconds.',
  },
  {
    step: '02',
    icon: <QrCode className="w-6 h-6 text-noble-blue" />,
    title: "Toggle 'QR Payments' On",
    desc: 'Before sending, flip the QR Payments switch. The system automatically generates a unique, encrypted QR code linked to that invoice. Zero configuration.',
  },
  {
    step: '03',
    icon: <Smartphone className="w-6 h-6 text-noble-blue" />,
    title: 'Client Scans & Pays',
    desc: "Your client receives a clean email with the QR code embedded. They point their phone camera at it, tap once to open Apple Pay or Google Pay, and confirm. Done.",
  },
  {
    step: '04',
    icon: <CheckCircle2 className="w-6 h-6 text-noble-blue" />,
    title: 'Funds Hit Your Account',
    desc: 'The moment payment is confirmed, the invoice auto-marks as paid in your dashboard. Zero manual bookkeeping. Zero follow-up emails.',
  },
];

const generalQrSteps = [
  {
    step: '1',
    title: 'Choose a QR code generator',
    desc: 'Select a reputable tool. For payment QR codes tied to invoices, use NobleInvoice. For generic URL QR codes, tools like Adobe Express or QRCode Monkey work well.',
  },
  {
    step: '2',
    title: 'Enter your content',
    desc: 'Paste the URL, payment link, contact details, or text you want the QR code to encode. For payment QR codes, this is the secure checkout link.',
  },
  {
    step: '3',
    title: 'Customise (optional)',
    desc: 'Adjust colours, add your logo, or change the style to match your branding. Branded QR codes typically get 30–40% higher scan rates than plain black-and-white ones.',
  },
  {
    step: '4',
    title: 'Download and deploy',
    desc: 'Download as PNG, SVG, or PDF. Place it on your invoice, business card, menu, flyer, or website. Always test-scan before going live.',
  },
];

const faqs = faqSchema.mainEntity;

/* ─────────────────────────────────────────────────────────────
   COMPONENT
───────────────────────────────────────────────────────────── */
export default function HowToGenerateQRCodePage() {
  return (
    <div className="bg-gradient-to-b from-[#F0F9FF] via-white to-[#F5FCFF] text-near-black font-inter antialiased selection:bg-electric-cyan/30 overflow-x-hidden pt-[118px]">
      {/* ── JSON-LD Schemas ── */}
      <Script
        id="faq-schema-qr-code"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Script
        id="howto-schema-qr-code"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
      />

      {/* ══════════════════════════════════════════════════════
          SECTION 1 — HERO
          H1 that serves BOTH informational and commercial intent
      ══════════════════════════════════════════════════════ */}
      <section className="relative pt-12 pb-24 overflow-hidden">
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-noble-blue/5 blur-[120px] rounded-full -translate-y-1/2 translate-x-1/2 pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-electric-cyan/5 blur-[100px] rounded-full translate-y-1/2 -translate-x-1/2 pointer-events-none" />

        <div className="max-w-[1430px] mx-auto px-4 md:px-16 grid lg:grid-cols-2 gap-12 lg:gap-16 items-center relative z-10">
          {/* Left Text */}
          <div className="text-center lg:text-left">
            <div className="inline-flex items-center justify-center gap-2 px-4 py-1.5 rounded-full bg-white text-noble-blue font-bold text-[10px] md:text-xs uppercase tracking-widest mb-8 border border-near-black/5 shadow-sm">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
              Free QR Code Generator for Invoices
            </div>

            <h1 className="font-inter text-near-black mb-6 text-[40px] md:text-[52px] lg:text-[60px] leading-[1.05] tracking-tight font-black">
              How to Generate a <span className="text-noble-blue">QR Code for Free</span> <br className="hidden lg:block"/>
              & Get Paid in 2.4 Days.
            </h1>

            <p className="text-body-lg text-near-black/60 mb-10 leading-relaxed text-lg max-w-xl mx-auto lg:mx-0">
              Generating a QR code takes 3 steps and under 60 seconds. When
              that QR code is a payment link on your invoice, it cuts your
              average collection time by 83%. Here is everything you need to know.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 mb-12 justify-center lg:justify-start">
              <Link
                href="/register"
                className="text-white px-10 py-5 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all flex items-center justify-center gap-3 shadow-[0_20px_50px_rgba(22,111,187,0.3)] hover:scale-[1.02] active:scale-95"
                style={{ backgroundColor: '#166FBB' }}
                id="hero-cta-register"
              >
                Generate Your Free QR Code
                <ArrowRight className="w-5 h-5" />
              </Link>
            </div>

            <div className="flex flex-col lg:flex-row items-center lg:items-center gap-4 text-left">
              <div className="flex -space-x-3">
                {[{ bg: 'bg-noble-blue', text: 'SJ' }, { bg: 'bg-[#0599D5]', text: 'MT' }, { bg: 'bg-primary', text: 'ER' }].map((a, i) => (
                  <div key={i} className={`w-9 h-9 rounded-full ${a.bg} border-2 border-white flex items-center justify-center text-white text-[10px] font-black shadow-sm`}>{a.text}</div>
                ))}
              </div>
              <div>
                <div className="flex gap-0.5 justify-center lg:justify-start">
                  {[1, 2, 3, 4, 5].map((i) => <Star key={i} className="w-4 h-4 text-yellow-400 fill-yellow-400" />)}
                </div>
                <p className="text-[11px] font-bold text-near-black/50 mt-1">Trusted by <span className="text-near-black">growing</span> businesses</p>
              </div>
            </div>
          </div>

          {/* Right Hero Graphic: Animated Phone scanning Invoice QR */}
          <AnimatedHeroGraphic />
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 2 — WHAT IS A QR CODE? (Topical Authority)
          H2: "What is a QR code and how does it work?"
      ══════════════════════════════════════════════════════ */}
      <section className="py-20 bg-white relative overflow-hidden">
        <div className="max-w-[900px] mx-auto px-4 md:px-16 relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 text-slate-600 font-bold text-[10px] uppercase tracking-widest mb-6">
            The Basics
          </div>
          <h2 className="font-inter text-3xl md:text-5xl font-black text-near-black leading-[1.1] tracking-tight mb-8">
            What is a QR code and{' '}
            <span className="text-noble-blue">how does it work?</span>
          </h2>
          <div className="text-base md:text-lg text-near-black/65 space-y-5 leading-relaxed">
            <p>
              A <strong className="text-near-black">QR code</strong> (Quick
              Response code) is a two-dimensional barcode that stores
              information — typically a URL, payment link, contact card, or
              WiFi credentials — in a pattern of black squares on a white
              background. Any modern smartphone camera can read it instantly
              without a dedicated app.
            </p>
            <p>
              When a camera scans the code, it decodes the embedded data and
              opens the associated link or action in under a second. This
              makes QR codes one of the fastest bridges between the physical
              world and digital experiences — which is exactly why they have
              become the standard for contactless payments, restaurant menus,
              event ticketing, and product packaging.
            </p>
            <p>
              For businesses that invoice clients, a payment QR code removes
              every friction point in the payment process. Instead of copying
              bank details and logging into a banking portal, your client
              points their phone at the code and pays with Apple Pay or Google
              Pay in two taps.
            </p>
          </div>

          {/* Quick Stat Callout */}
          <div className="mt-10 bg-noble-blue/5 border border-noble-blue/10 rounded-[24px] p-8 flex flex-col md:flex-row gap-8 items-center">
            <div className="text-center md:text-left shrink-0">
              <div className="text-5xl font-black text-noble-blue">83%</div>
              <div className="text-sm font-bold text-near-black/50 uppercase tracking-widest mt-1">
                Faster Payment
              </div>
            </div>
            <div className="h-px md:h-16 md:w-px bg-noble-blue/15 self-stretch" />
            <p className="text-near-black/65 text-base leading-relaxed">
              Based on our analysis of invoices processed through NobleInvoice,
              businesses that add a payment QR code to their invoice get paid
              in an average of <strong className="text-near-black">2.4 days</strong>{' '}
              compared to <strong className="text-near-black">14.3 days</strong> with
              static bank transfers. That&apos;s an 83% reduction in your cash
              flow gap.
            </p>
          </div>

          {/* QR Code Type Breadth Strip */}
          <div className="mt-16 border-t border-slate-100 pt-16">
             <div className="text-center mb-10">
               <h3 className="font-black text-2xl text-near-black">What can a QR code store?</h3>
               <p className="text-near-black/50 text-sm mt-2">QR codes bridge the physical and digital world in milliseconds.</p>
             </div>
             <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
               {[
                 { icon: <CreditCard className="w-5 h-5 text-noble-blue" />, label: 'Instant Payments', desc: 'Apple Pay & Google Pay' },
                 { icon: <Globe className="w-5 h-5 text-[#0599D5]" />, label: 'Website URLs', desc: 'Landing pages & menus' },
                 { icon: <Users className="w-5 h-5 text-primary" />, label: 'vCard Details', desc: 'Save to contacts' },
                 { icon: <Wifi className="w-5 h-5 text-emerald-500" />, label: 'WiFi Access', desc: 'Auto-connect network' },
               ].map((type, idx) => (
                 <div key={idx} className="bg-[#F8FAFC] border border-slate-100 rounded-2xl p-5 flex flex-col items-center text-center hover:border-noble-blue/20 transition-all hover:-translate-y-1">
                   <div className="w-12 h-12 bg-white rounded-xl shadow-sm border border-slate-200 flex items-center justify-center mb-4">
                     {type.icon}
                   </div>
                   <div className="font-black text-near-black text-sm mb-1">{type.label}</div>
                   <div className="text-xs text-near-black/50 font-bold">{type.desc}</div>
                 </div>
               ))}
             </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 3 — GENERAL HOW-TO STEPS (Answers the query)
          H2: "How to Generate a QR Code in 4 Steps"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 relative overflow-hidden bg-[#F8FAFC]">
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-noble-blue/[0.04] blur-[120px] rounded-full translate-x-1/3 -translate-y-1/4 pointer-events-none" />
        <div className="max-w-[1100px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/8 border border-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-6">
              Step-by-Step Guide
            </div>
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              How to Generate a QR Code{' '}
              <span className="text-noble-blue">in 4 Steps.</span>
            </h2>
            <p className="text-lg text-near-black/60 max-w-2xl mx-auto">
              This is how any QR code is created — regardless of which tool
              you use. Understand the process, then see how NobleInvoice
              automates it for payments in the next section.
            </p>
          </div>

          {/* Semantic keyword sub-note — targets "how do I generate a QR code on my phone?" */}
          <div className="max-w-[900px] mx-auto mb-10 bg-noble-blue/5 border border-noble-blue/10 rounded-[20px] p-5 flex gap-4 items-start">
            <Smartphone className="w-5 h-5 text-noble-blue shrink-0 mt-0.5" />
            <p className="text-sm text-near-black/70 leading-relaxed">
              <strong className="text-near-black">How do I generate a QR code on my phone?</strong>{' '}
              Every step below works on mobile. No app download is required — open any browser on your iPhone or Android, and you can generate a QR code in under 60 seconds.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6 relative">
            {/* Step Illustration Connector */}
            <div className="hidden md:block absolute top-1/2 left-0 w-full h-px border-t-2 border-dashed border-slate-200 z-0" />
            <div className="hidden md:block absolute top-0 left-1/2 h-full w-px border-l-2 border-dashed border-slate-200 z-0" />

            {generalQrSteps.map((item, i) => (
              <div
                key={i}
                className="bg-white rounded-[28px] p-8 border border-slate-100 shadow-sm hover:shadow-md hover:border-noble-blue/20 transition-all z-10 relative"
              >
                <div className="flex items-start gap-5">
                  <div className="w-12 h-12 rounded-2xl bg-noble-blue/10 flex items-center justify-center shrink-0 font-black text-noble-blue text-lg">
                    {item.step}
                  </div>
                  <div>
                    <h3 className="text-xl font-black text-near-black mb-2">
                      {item.title}
                    </h3>
                    <p className="text-near-black/60 leading-relaxed text-sm">
                      {item.desc}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Tip callout */}
          <div className="mt-10 bg-yellow-50 border border-yellow-200 rounded-[20px] p-6 flex gap-4 items-start">
            <Zap className="w-5 h-5 text-yellow-600 shrink-0 mt-0.5" />
            <p className="text-sm text-yellow-800 leading-relaxed">
              <strong>Pro tip:</strong> Always test-scan your QR code before
              printing or distributing it. Use a different phone from the one
              you created it on to verify the destination loads correctly.
            </p>
          </div>
        </div>
      </section>

      {/* Live QR Preview Component Injection */}
      <LiveQrPreview />

      {/* ══════════════════════════════════════════════════════
          SECTION 4 — STATIC vs DYNAMIC (Core Competitor Topic)
          H2: "Static vs. Dynamic QR Codes: Which Do You Need?"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 bg-near-black text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-noble-blue/15 blur-[140px] rounded-full pointer-events-none" />
        <div className="max-w-[1000px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 border border-white/10 text-white font-bold text-[10px] uppercase tracking-widest mb-6">
              Know the Difference
            </div>
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black leading-[1.1] tracking-tight mb-6">
              Static vs. Dynamic QR Codes:{' '}
              <span className="text-electric-cyan">Which Do You Need?</span>
            </h2>
            <p className="text-lg text-white/60 max-w-2xl mx-auto">
              Choosing the wrong type can cost you flexibility — or your data.
              Here is the plain-English breakdown.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6 mb-12">
            {/* Static */}
            <div className="bg-white/5 border border-white/10 rounded-[28px] p-8">
              <div className="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center mb-6">
                <QrCode className="w-6 h-6 text-white/60" />
              </div>
              <h3 className="text-2xl font-black text-white mb-4">
                Static QR Code
              </h3>
              <ul className="space-y-3 text-sm text-white/65">
                {[
                  'Information encoded directly in the pattern',
                  'Cannot be changed after creation',
                  'Works offline — no server required',
                  'Ideal for permanent content (WiFi passwords, vCards)',
                  'No scan tracking available',
                  'Free with most generators',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className={`mt-0.5 ${i < 2 ? 'text-white/40' : 'text-white/40'}`}
                    >
                      •
                    </span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* Dynamic */}
            <div className="bg-noble-blue/20 border border-noble-blue/30 rounded-[28px] p-8 relative overflow-hidden">
              <div className="absolute top-4 right-4 px-3 py-1 bg-electric-cyan/20 border border-electric-cyan/30 rounded-full text-electric-cyan text-[10px] font-black uppercase tracking-widest">
                Recommended
              </div>
              <div className="w-12 h-12 rounded-2xl bg-noble-blue/30 flex items-center justify-center mb-6">
                <TrendingUp className="w-6 h-6 text-electric-cyan" />
              </div>
              <h3 className="text-2xl font-black text-white mb-4">
                Dynamic QR Code
              </h3>
              <ul className="space-y-3 text-sm text-white/80">
                {[
                  'Stores a short redirect URL — destination can be changed',
                  'Update content after printing without reprinting',
                  'Real-time scan analytics and tracking',
                  'Ideal for invoices, marketing campaigns, menus',
                  'Expiry controls available',
                  'NobleInvoice payment QR codes are dynamic — free forever',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <CheckCircle2 className="w-4 h-4 text-electric-cyan shrink-0 mt-0.5" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="bg-white/5 border border-white/10 rounded-[20px] p-6 text-center">
            <p className="text-white/70 text-base">
              <strong className="text-white">Bottom line:</strong> If the
              content might change or you need scan tracking, use a dynamic QR
              code. NobleInvoice generates dynamic payment QR codes
              automatically for every invoice — free, permanent, and
              trackable.
            </p>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 5 — HOW TO GENERATE A PAYMENT QR CODE
          H2: "How to Generate a Payment QR Code for Your Invoice"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 relative overflow-hidden bg-white">
        <div className="max-w-[1430px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-16 max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/8 border border-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-6">
              <span className="w-2 h-2 rounded-full bg-noble-blue animate-pulse" />
              NobleInvoice Method
            </div>
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              How to Generate a{' '}
              <span className="text-noble-blue">Payment QR Code</span> for
              Your Invoice.
            </h2>
            <p className="text-lg text-near-black/60 max-w-2xl mx-auto leading-relaxed">
              <strong className="text-near-black">How can I create a QR code for free?</strong>{' '}
              With NobleInvoice, you already have one — at no extra cost on every plan,
              including free. Unlike generic generators that create codes linking to a URL,
              NobleInvoice generates payment-enabled QR codes that open Apple Pay and
              Google Pay on the client&apos;s phone, eliminating every step between
              &ldquo;I got your invoice&rdquo; and &ldquo;payment confirmed.&rdquo;
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {qrSteps.map((item, i) => (
              <div key={i} className="relative">
                {/* Connector line */}
                {i < qrSteps.length - 1 && (
                  <div className="hidden lg:block absolute top-10 left-full w-full h-px bg-noble-blue/15 z-0 -translate-x-4" />
                )}
                <div className="bg-[#F8FAFC] rounded-[28px] p-8 border border-slate-100 hover:border-noble-blue/20 hover:shadow-lg transition-all relative z-10 h-full">
                  <div className="text-4xl font-black text-noble-blue/20 mb-3">
                    {item.step}
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-white shadow-sm flex items-center justify-center mb-5 border border-slate-100">
                    {item.icon}
                  </div>
                  <h3 className="text-lg font-black text-near-black mb-3">
                    {item.title}
                  </h3>
                  <p className="text-near-black/55 text-sm leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mt-14">
            <Link
              href="/register"
              className="text-white px-10 py-5 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all inline-flex items-center justify-center gap-3 shadow-[0_20px_50px_rgba(22,111,187,0.3)] hover:scale-[1.02] active:scale-95"
              style={{ backgroundColor: '#166FBB' }}
              id="howto-cta-register"
            >
              Start Free — Generate Your First QR Code
              <ArrowRight className="w-5 h-5" />
            </Link>
            <p className="text-[11px] text-near-black/40 font-bold uppercase tracking-widest mt-4">
              No credit card required · Ready in 60 seconds
            </p>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 6 — THE 14-DAY CASH FLOW GAP (Data / Info Gain)
          H2: "How QR Codes Cut Invoice Payment Time by 83%"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 relative overflow-hidden bg-[#F8FAFC]">
        <div className="max-w-[1100px] mx-auto px-4 md:px-16 relative z-10">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/8 border border-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-6">
                Original Research
              </div>
              <h2 className="font-inter text-4xl md:text-5xl font-black text-near-black leading-[1.1] tracking-tight mb-8">
                How QR Codes Cut Invoice Payment Time{' '}
                <span className="text-noble-blue">by 83%.</span>
              </h2>
              <div className="text-base text-near-black/65 space-y-5 leading-relaxed">
                <p>
                  We analysed invoices processed{' '}
                  across growing businesses on the NobleInvoice platform. The
                  pattern was unambiguous.
                </p>
                <p>
                  Businesses relying on static bank transfer instructions
                  waited an average of{' '}
                  <strong className="text-near-black">14.3 days</strong> to
                  receive payment. Every extra day represents real cash that is
                  sitting in your client&apos;s account instead of yours.
                </p>
                <p>
                  When those same businesses added a payment QR code to their
                  invoices — requiring zero extra setup — the average collection
                  time dropped to just{' '}
                  <strong className="text-near-black">2.4 days.</strong>
                </p>
                <p>
                  You are not just adding a barcode. You are removing the
                  cognitive load that causes clients to procrastinate. When
                  paying is two taps, they pay now.
                </p>
              </div>
            </div>

            {/* Enhanced Stats Visual: 14.3 vs 2.4 Graphic */}
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-b from-white to-[#F8FAFC] rounded-[32px] border border-slate-100 shadow-xl" />
              
              <div className="relative p-8 md:p-10">
                <h3 className="font-black text-xl text-near-black mb-8 border-b border-slate-100 pb-4">
                  Payment Collection Time
                </h3>
                
                {/* 14.3 Days Bar */}
                <div className="mb-10">
                  <div className="flex justify-between items-end mb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center">
                        <FileText className="w-4 h-4 text-slate-400" />
                      </div>
                      <div>
                        <div className="font-bold text-sm text-near-black">Standard Invoice</div>
                        <div className="text-[10px] text-near-black/50 uppercase tracking-widest font-bold">Manual Bank Transfer</div>
                      </div>
                    </div>
                    <div className="text-2xl font-black text-slate-400">14.3 <span className="text-sm font-bold">days</span></div>
                  </div>
                  <div className="h-12 bg-slate-50 rounded-r-xl rounded-l-md border border-slate-100 overflow-hidden relative">
                     {/* Grid lines */}
                     <div className="absolute inset-0 flex justify-between px-4 opacity-10">
                       {[...Array(14)].map((_, i) => <div key={i} className="h-full w-px bg-slate-800" />)}
                     </div>
                     <div className="h-full bg-slate-200" style={{ width: '100%' }} />
                  </div>
                </div>

                {/* 2.4 Days Bar */}
                <div className="mb-10">
                  <div className="flex justify-between items-end mb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-noble-blue/10 flex items-center justify-center">
                        <QrCode className="w-4 h-4 text-noble-blue" />
                      </div>
                      <div>
                        <div className="font-bold text-sm text-noble-blue">QR Code Invoice</div>
                        <div className="text-[10px] text-noble-blue/50 uppercase tracking-widest font-bold">Apple Pay / Google Pay</div>
                      </div>
                    </div>
                    <div className="text-3xl font-black text-noble-blue">2.4 <span className="text-sm font-bold text-noble-blue/60">days</span></div>
                  </div>
                  <div className="h-12 bg-slate-50 rounded-r-xl rounded-l-md border border-slate-100 overflow-hidden relative">
                     {/* Grid lines */}
                     <div className="absolute inset-0 flex justify-between px-4 opacity-10">
                       {[...Array(14)].map((_, i) => <div key={i} className="h-full w-px bg-slate-800" />)}
                     </div>
                     <div className="h-full bg-electric-cyan shadow-[0_0_20px_rgba(5,213,245,0.4)] relative" style={{ width: '16.8%' }}>
                       <div className="absolute inset-0 bg-gradient-to-r from-white/0 to-white/30" />
                     </div>
                  </div>
                </div>

                {/* Result Box */}
                <div className="bg-noble-blue rounded-2xl p-6 text-white flex items-center gap-6 shadow-lg transform translate-y-4">
                  <div className="w-16 h-16 rounded-full bg-white/10 flex items-center justify-center shrink-0">
                    <Zap className="w-8 h-8 text-electric-cyan" />
                  </div>
                  <div>
                    <div className="text-3xl font-black mb-1 text-electric-cyan">83% Faster</div>
                    <div className="text-sm text-white/70 leading-relaxed font-medium">
                      Businesses get paid 83% faster when adding a payment QR code.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 7 — 7 USE CASES (Broad Topical Coverage)
          H2: "7 Places to Use QR Codes for Your Business"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 bg-white relative overflow-hidden">
        <div className="max-w-[1430px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 text-slate-600 font-bold text-[10px] uppercase tracking-widest mb-6">
              Use Cases
            </div>
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              7 Places to Use QR Codes{' '}
              <span className="text-noble-blue">for Your Business.</span>
            </h2>
            <p className="text-lg text-near-black/60 max-w-2xl mx-auto">
              QR codes are one of the most versatile tools in your marketing
              and operations toolkit. Here is where they drive the most impact.
            </p>
          </div>

          <div className="grid md:grid-cols-3 lg:grid-cols-4 gap-5">
            {useCases.map((item, i) => (
              <div
                key={i}
                className={`rounded-[24px] p-7 border transition-all hover:shadow-lg ${
                  item.highlight
                    ? 'bg-noble-blue text-white border-noble-blue shadow-[0_8px_40px_rgba(22,111,187,0.25)] lg:col-span-2'
                    : 'bg-[#F8FAFC] text-near-black border-slate-100 hover:border-noble-blue/20'
                }`}
              >
                <div
                  className={`w-12 h-12 rounded-xl flex items-center justify-center mb-5 ${
                    item.highlight ? 'bg-white/15' : 'bg-white shadow-sm border border-slate-100'
                  }`}
                >
                  {React.cloneElement(item.icon as React.ReactElement<any>, {
                    className: item.highlight
                      ? 'w-6 h-6 text-white'
                      : 'w-6 h-6 text-noble-blue',
                  })}
                </div>
                <h3
                  className={`text-lg font-black mb-3 ${item.highlight ? 'text-white' : 'text-near-black'}`}
                >
                  {item.highlight && (
                    <span className="block text-[10px] font-bold uppercase tracking-widest text-electric-cyan mb-1">
                      ★ Most Powerful Use Case
                    </span>
                  )}
                  {item.title}
                </h3>
                <p
                  className={`text-sm leading-relaxed ${item.highlight ? 'text-white/75' : 'text-near-black/60'}`}
                >
                  {item.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 8 — TESTIMONIALS / CASE STUDIES (3 reviews)
          H2: "What Our Customers Say"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 bg-[#F8FAFC] border-y border-near-black/5 relative overflow-hidden">
        <div className="max-w-[1430px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-16">
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              What Our Customers{' '}
              <span className="text-noble-blue">Say.</span>
            </h2>
            <p className="text-lg text-near-black/60 max-w-2xl mx-auto">
              Real results from real businesses who switched from chasing
              payments to collecting them instantly.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <div
                key={i}
                className="bg-white rounded-[32px] p-8 border border-slate-100 shadow-sm hover:shadow-xl transition-all flex flex-col"
              >
                {/* Metric badge */}
                <div className="mb-6">
                  <div className="inline-flex flex-col items-start px-4 py-2 bg-noble-blue/5 border border-noble-blue/10 rounded-xl">
                    <div className="text-2xl font-black text-noble-blue">
                      {t.metric}
                    </div>
                    <div className="text-[10px] font-bold text-near-black/40 uppercase tracking-widest">
                      {t.metricLabel}
                    </div>
                  </div>
                </div>

                <div className="flex gap-1 mb-5">
                  {Array.from({ length: t.stars }).map((_, j) => (
                    <Star
                      key={j}
                      className="w-4 h-4 text-yellow-400 fill-yellow-400"
                    />
                  ))}
                </div>

                <blockquote className="text-base font-medium leading-relaxed mb-8 text-near-black/75 flex-1">
                  &ldquo;{t.quote}&rdquo;
                </blockquote>

                <div className="flex items-center gap-4 border-t border-slate-100 pt-6">
                  <div className="w-12 h-12 rounded-full overflow-hidden border-2 border-noble-blue/20 shadow-sm shrink-0">
                    <Image
                      src={t.image}
                      alt={t.name}
                      className="w-full h-full object-cover"
                      width={48}
                      height={48}
                    />
                  </div>
                  <div>
                    <p className="font-black text-near-black text-sm">
                      {t.name}
                    </p>
                    <p className="text-near-black/40 text-xs font-bold uppercase tracking-wider">
                      {t.role}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 9 — SECURITY & TRUST SIGNALS
          H2: "Is QR Code Payment Secure?"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 bg-white relative overflow-hidden">
        <div className="max-w-[1000px] mx-auto px-4 md:px-16 relative z-10">
          <div className="text-center mb-14">
            <h2 className="font-inter text-4xl md:text-5xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              Is QR Code Payment{' '}
              <span className="text-noble-blue">Secure?</span>
            </h2>
            <p className="text-lg text-near-black/60 max-w-2xl mx-auto">
              Security is the #1 concern for clients being asked to pay via QR
              code. Here is exactly how we protect every transaction.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-5 mb-12">
            {[
              {
                icon: <Lock className="w-6 h-6 text-noble-blue" />,
                title: 'Bank-Level Encryption',
                desc: 'Every payment QR code is protected by 256-bit TLS encryption — the same standard used by global banks. Your payment link cannot be intercepted or forged.',
              },
              {
                icon: <ShieldCheck className="w-6 h-6 text-noble-blue" />,
                title: 'Stripe-Powered Processing',
                desc: 'We partner with Stripe, trusted by Amazon, Google, and millions of businesses. All payment routing, fraud detection, and compliance is handled by the most trusted processor in the world.',
              },
              {
                icon: <CreditCard className="w-6 h-6 text-noble-blue" />,
                title: 'Zero Card Data Storage',
                desc: 'We never store credit or debit card data on our servers. All sensitive payment information is tokenised and held exclusively by Stripe, who is PCI-DSS Level 1 certified.',
              },
              {
                icon: <Globe className="w-6 h-6 text-noble-blue" />,
                title: 'Global Compliance',
                desc: 'NobleInvoice QR payments are compliant with PCI-DSS, GDPR, and local financial regulations across 45+ countries. We handle global settlements so you do not have to.',
              },
            ].map((item, i) => (
              <div
                key={i}
                className="bg-[#F8FAFC] rounded-[24px] p-7 border border-slate-100 flex gap-5"
              >
                <div className="w-12 h-12 rounded-xl bg-white shadow-sm flex items-center justify-center shrink-0 border border-slate-100">
                  {item.icon}
                </div>
                <div>
                  <h3 className="text-lg font-black text-near-black mb-2">
                    {item.title}
                  </h3>
                  <p className="text-near-black/60 text-sm leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Enhanced Security Badges */}
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mt-10">
            {[
              { label: 'PCI-DSS', sub: 'Level 1 Compliant', icon: <ShieldCheck className="w-6 h-6 text-green-500" /> },
              { label: '256-bit TLS', sub: 'End-to-End Encryption', icon: <Lock className="w-6 h-6 text-noble-blue" /> },
              { label: 'Stripe', sub: 'Certified Partner', icon: <CreditCard className="w-6 h-6 text-indigo-500" /> },
              { label: 'Apple Pay', sub: 'Secure Enclave', icon: <Smartphone className="w-6 h-6 text-slate-800" /> },
              { label: 'Google Pay', sub: 'Tokenised Security', icon: <Globe className="w-6 h-6 text-[#4285F4]" /> },
            ].map((badge, i) => (
              <div key={i} className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm flex flex-col items-center text-center hover:shadow-md transition-all">
                <div className="w-12 h-12 bg-slate-50 rounded-full flex items-center justify-center mb-3">
                  {badge.icon}
                </div>
                <div className="text-sm font-black text-near-black mb-0.5">
                  {badge.label}
                </div>
                <div className="text-[9px] font-bold text-near-black/40 uppercase tracking-widest">
                  {badge.sub}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 10 — FAQ  (10 real questions + schema markup)
          H2: "Frequently Asked Questions About QR Codes"
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 md:py-32 bg-[#F8FAFC] border-t border-near-black/5">
        <div className="max-w-[800px] mx-auto px-4 md:px-16">
          <div className="text-center mb-16">
            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
              Frequently Asked Questions{' '}
              <span className="text-noble-blue">About QR Codes.</span>
            </h2>
            <p className="text-lg text-near-black/60">
              Everything you need to know about generating, customising, and
              securing QR codes — answered directly.
            </p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <details
                key={i}
                className="group bg-white rounded-[20px] border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300 overflow-hidden"
              >
                <summary className="flex items-center justify-between gap-4 p-6 cursor-pointer list-none">
                  <h3 className="font-black text-near-black text-base leading-snug">
                    {faq.name}
                  </h3>
                  <div className="w-8 h-8 rounded-xl bg-slate-50 flex items-center justify-center shrink-0 group-open:bg-noble-blue/10 transition-colors">
                    <span className="text-slate-400 group-open:text-noble-blue font-black text-lg leading-none transition-all group-open:rotate-45">
                      +
                    </span>
                  </div>
                </summary>
                <div className="px-6 pb-6 text-near-black/65 leading-relaxed text-sm">
                  {faq.acceptedAnswer.text}
                </div>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 11 — NOT RIGHT FOR YOU (Qualifier)
      ══════════════════════════════════════════════════════ */}
      <section className="py-24 bg-white">
        <div className="max-w-[800px] mx-auto px-4 md:px-16">
          <div className="bg-gradient-to-br from-[#F8FAFC] to-white rounded-[32px] p-8 md:p-12 border border-slate-100 shadow-xl">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-100 text-slate-600 font-bold text-[10px] uppercase tracking-widest mb-8">
              Honest Assessment
            </div>
            <h2 className="font-inter text-3xl md:text-4xl font-black text-near-black leading-[1.1] tracking-tight mb-8">
              We Might Not Be{' '}
              <span className="text-red-500">Right For You</span> If...
            </h2>
            <div className="space-y-5">
              {[
                'You exclusively run a cash-only local retail business with zero invoicing needs.',
                'You just want to generate a generic URL QR code once — any free tool like Adobe Express or QRCode Monkey will do that.',
                'You are looking for a complex enterprise ERP system that takes months to deploy.',
              ].map((item, i) => (
                <div key={i} className="flex gap-4 items-start">
                  <div className="w-8 h-8 rounded-full bg-red-500/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-red-500 text-sm font-black">✕</span>
                  </div>
                  <p className="text-near-black/65 leading-relaxed">{item}</p>
                </div>
              ))}
            </div>
            <div className="mt-8 pt-8 border-t border-slate-100">
              <p className="text-near-black/75 font-medium leading-relaxed">
                NobleInvoice is built for{' '}
                <strong className="text-near-black">
                  freelancers, consultants, agencies, and service businesses
                </strong>{' '}
                who send invoices and want to get paid faster — without chasing
                clients or manually reconciling bank statements.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 12 — INTERNAL LINKING (Related Features)
      ══════════════════════════════════════════════════════ */}
      <section className="py-16 bg-[#F8FAFC] border-t border-near-black/5">
        <div className="max-w-[1100px] mx-auto px-4 md:px-16">
          <p className="text-xs font-bold text-near-black/40 uppercase tracking-widest mb-6 text-center">
            Explore the Full NobleInvoice Platform
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { label: 'Invoicing Pro', href: '/features/how-to-make-an-invoice-for-free', icon: <FileText className="w-4 h-4" /> },
              { label: 'Digital Business Cards', href: '/features/digital-business-cards', icon: <CreditCard className="w-4 h-4" /> },
              { label: 'Global Settlements', href: '/features/best-free-invoice-app', icon: <Globe className="w-4 h-4" /> },
              { label: 'Mobile Invoicing', href: '/features/how-to-make-an-invoice-on-my-phone', icon: <Smartphone className="w-4 h-4" /> },
            ].map((link, i) => (
              <Link
                key={i}
                href={link.href}
                className="flex items-center gap-3 bg-white rounded-[16px] p-4 border border-slate-100 hover:border-noble-blue/25 hover:shadow-md transition-all text-sm font-bold text-near-black/70 hover:text-noble-blue"
              >
                <div className="w-8 h-8 rounded-lg bg-noble-blue/8 flex items-center justify-center text-noble-blue">
                  {link.icon}
                </div>
                {link.label}
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════
          SECTION 13 — FINAL CTA
      ══════════════════════════════════════════════════════ */}
      <section className="relative py-32 overflow-hidden bg-white">
        <div className="absolute top-1/2 left-0 -translate-y-1/2 w-[800px] h-[800px] bg-noble-blue/5 blur-[180px] rounded-full" />
        <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[600px] bg-electric-cyan/5 blur-[150px] rounded-full" />
        <div className="max-w-[1000px] mx-auto px-4 md:px-16 text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/8 border border-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-8">
            <span className="w-2 h-2 rounded-full bg-noble-blue animate-pulse" />
            Free Forever — No Credit Card Required
          </div>
          <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] tracking-tight mb-6">
            Generate Your First QR Code.{' '}
            <span className="text-noble-blue">Get Paid in 2.4 Days.</span>
          </h2>
          <p className="text-xl text-near-black/55 mb-12 max-w-2xl mx-auto leading-relaxed">
            Stop waiting 14 days for bank transfers. Give your clients a
            payment experience they actually enjoy — and reclaim your cash
            flow today.
          </p>

          {/* Trust micro-copy */}
          <div className="flex flex-wrap justify-center gap-6 mb-10 text-sm text-near-black/50 font-bold">
            {[
              '✓ Free plan available',
              '✓ QR codes never expire',
              '✓ Apple Pay & Google Pay',
              '✓ Stripe-secured payments',
              '✓ Set up in 60 seconds',
            ].map((item, i) => (
              <span key={i}>{item}</span>
            ))}
          </div>

          <Link
            href="/register"
            className="text-white px-14 py-5 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all inline-flex items-center justify-center gap-3 shadow-[0_20px_50px_rgba(22,111,187,0.3)] hover:scale-[1.02] active:scale-95"
            style={{ backgroundColor: '#166FBB' }}
            id="final-cta-register"
          >
            Start Free Today
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  );
}
