import { MindMapModel, MindMapNode } from '@/types';

/**
 * Utility to convert MindMapModel JSON into a hierarchical Markdown outline.
 */
export const exportToMarkdown = (mindMap: MindMapModel): string => {
    if (!mindMap.nodes || mindMap.nodes.length === 0) return '';

    const rootNode = mindMap.nodes.find(n => n.type === 'central');
    if (!rootNode) return '';

    let markdown = `# Mind Map: ${mindMap.title}\n\n`;
    markdown += `**Central Topic:** ${rootNode.title}\n\n`;
    markdown += `--- \n\n`;

    const processedIds = new Set<string>();

    const traverse = (nodeId: string, depth: number) => {
        if (processedIds.has(nodeId)) return;
        processedIds.add(nodeId);

        const node = mindMap.nodes.find(n => n.id === nodeId);
        if (!node) return;

        const indent = '  '.repeat(depth);
        const prefix = depth === 0 ? '##' : '-';
        
        markdown += `${indent}${prefix} ${node.title}\n`;
        
        if (node.description) {
            markdown += `${indent}  > ${node.description}\n`;
        }

        if (node.sourceUrls && node.sourceUrls.length > 0) {
            markdown += `${indent}  *Sources: ${node.sourceUrls.join(', ')}*\n`;
        }

        if (node.weight !== undefined) {
          const weightLabel = node.weight > 0.7 ? '🔥 Critical' : node.weight > 0.4 ? '⚡ High' : '🌱 Emerging';
          markdown += `${indent}  *[Density: ${weightLabel}]*\n`;
        }

        if (node.childIds && node.childIds.length > 0) {
            node.childIds.forEach(childId => traverse(childId, depth + 1));
        }
    };

    traverse(rootNode.id, 0);

    markdown += `\n---\n*Generated by NobleInvoice AI Research Engine*`;

    return markdown;
};

