-- ==============================================================================
-- NOBLEGO: SUPABASE ROW LEVEL SECURITY (RLS) POLICIES
-- Execute this script in the Supabase SQL Editor after running the initial schema
-- ==============================================================================

-- Enable RLS on all tables to ensure data safety
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_scans ENABLE ROW LEVEL SECURITY;

-- Note for Development:
-- If you want the app to "just work" while you test, you can run the following
-- commands to allow all authenticated users full access to tables.
-- ONLY DO THIS FOR DEVELOPMENT. For production, write strict policies.
-- 
-- CREATE POLICY "Allow all to authenticated users" ON public.profiles FOR ALL TO authenticated USING (true);
-- (Repeat for each table)...

-- Below are some basic and secure baseline policies for the core apps:

-- PROFILES: Users can only see and update their own profile
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- EXPENSES: Linked strictly to user_id
CREATE POLICY "Users full access to own expenses" ON public.expenses FOR ALL USING (auth.uid() = user_id);

-- USER SESSIONS
CREATE POLICY "Users full access to own sessions" ON public.user_sessions FOR ALL USING (auth.uid() = user_id);

-- PAYMENT METHODS
CREATE POLICY "Users full access to own payment methods" ON public.payment_methods FOR ALL USING (auth.uid() = user_id);

-- FOLDERS & QR CODES: Owned by user
CREATE POLICY "Users full access to own folders" ON public.folders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users full access to own qr codes" ON public.qr_codes FOR ALL USING (auth.uid() = user_id);
-- Note: QR scans might need public insert access if they are generated by a public link hit.
CREATE POLICY "Public insert qr scans" ON public.qr_scans FOR INSERT WITH CHECK (true);

-- TEAMS: Access restricted by team_members table
CREATE POLICY "Users can view teams they belong to" ON public.teams FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.team_members WHERE team_members.team_id = teams.id AND team_members.user_id = auth.uid())
);
CREATE POLICY "Owners can manage teams" ON public.teams FOR ALL USING (
  owner_id = auth.uid() OR
  EXISTS (SELECT 1 FROM public.team_members WHERE team_members.team_id = teams.id AND team_members.user_id = auth.uid() AND team_members.role = 'owner')
);

-- TEAM MEMBERS
CREATE POLICY "Users can view members of their teams" ON public.team_members FOR SELECT USING (
  user_id = auth.uid() OR
  EXISTS (SELECT 1 FROM public.team_members AS tm WHERE tm.team_id = team_members.team_id AND tm.user_id = auth.uid())
);
CREATE POLICY "Owners and Admins manage team members" ON public.team_members FOR ALL USING (
  EXISTS (SELECT 1 FROM public.team_members AS tm WHERE tm.team_id = team_members.team_id AND tm.user_id = auth.uid() AND tm.role IN ('owner', 'admin'))
);

-- Note: Tables like `clients`, `products`, `invoices` rely on `team_id`.
-- You would create policies like:
-- CREATE POLICY "Access team clients" ON public.clients FOR ALL USING (
--   EXISTS (SELECT 1 FROM public.team_members WHERE team_members.team_id = clients.team_id AND team_members.user_id = auth.uid())
-- );
