-- ============================================================
-- NobleGo: Expense Management & Financial Health Migration
-- ============================================================

-- 1. Vendors Table (Suppliers you pay)
CREATE TABLE IF NOT EXISTS public.vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  category TEXT, -- e.g. 'Software', 'Rent', 'Hardware'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Vendors
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Team members can manage vendors" ON vendors;
CREATE POLICY "Team members can manage vendors" ON vendors FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

-- 2. Expense Categories (Standard set)
-- We can treat categories as a TEXT column with a standard set in Flutter,
-- but a table allows for user-defined categories later.
CREATE TABLE IF NOT EXISTS public.expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE, -- NULL for system-wide
  name TEXT NOT NULL,
  icon TEXT, -- Material icon name
  color TEXT, -- Hex color
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Standard Categories (only if table is empty)
INSERT INTO public.expense_categories (name, icon, color) 
SELECT * FROM (VALUES
  ('Marketing', 'campaign', '#EF4444'),
  ('Rent & Office', 'business', '#3B82F6'),
  ('Professional Services', 'gavel', '#7C3AED'),
  ('Software & SaaS', 'cloud_queue', '#2563EB'),
  ('Hardware & Assets', 'laptop', '#1E293B'),
  ('Travel & Transport', 'flight', '#F59E0B'),
  ('Salaries & Wages', 'group', '#10B981'),
  ('Utilities', 'lightbulb', '#FACC15'),
  ('Tax & Insurance', 'security', '#6B7280'),
  ('Other', 'more_horiz', '#94A3B8')
) AS tmp(name, icon, color)
WHERE NOT EXISTS (SELECT 1 FROM public.expense_categories LIMIT 1);

-- RLS for Categories
ALTER TABLE expense_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view system and own categories" ON expense_categories;
DROP POLICY IF EXISTS "Users can manage own categories" ON expense_categories;

CREATE POLICY "Users can view system and own categories" ON expense_categories 
  FOR SELECT USING (user_id IS NULL OR user_id = auth.uid());
CREATE POLICY "Users can manage own categories" ON expense_categories 
  FOR ALL USING (user_id = auth.uid());

-- 3. Expenses Table
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  vendor_id BIGINT REFERENCES public.vendors(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES public.expense_categories(id) ON DELETE SET NULL,
  amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  currency_code TEXT DEFAULT 'USD',
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  receipt_url TEXT, -- URL from 'receipts' bucket
  notes TEXT,
  is_recurring BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Expenses
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Team members can manage expenses" ON expenses;
CREATE POLICY "Team members can manage expenses" ON expenses FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff', 'accountant']::team_role[]));

-- 4. Receipts Storage Bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('receipts', 'receipts', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Users can upload receipts" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can view receipts" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete own receipts" ON storage.objects;

CREATE POLICY "Users can upload receipts" ON storage.objects 
  FOR INSERT WITH CHECK (bucket_id = 'receipts' AND auth.uid()::text = (storage.foldername(name))[1]);
CREATE POLICY "Anyone can view receipts" ON storage.objects 
  FOR SELECT USING (bucket_id = 'receipts');
CREATE POLICY "Users can delete own receipts" ON storage.objects 
  FOR DELETE USING (bucket_id = 'receipts' AND auth.uid()::text = (storage.foldername(name))[1]);
