-- ============================================================
-- NobleGo: Inventory & Product Management Migration
-- ============================================================

-- 1. Product Categories Table
CREATE TABLE IF NOT EXISTS public.product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Product Categories
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Team members can manage product categories" ON product_categories;
CREATE POLICY "Team members can manage product categories" ON product_categories FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

-- 2. Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  sku TEXT, -- Stock Keeping Unit
  description TEXT,
  unit_price NUMERIC(15,2) NOT NULL DEFAULT 0,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  track_inventory BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Team members can manage products" ON products;
CREATE POLICY "Team members can manage products" ON products FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

-- 3. Stock Ledger Table
CREATE TABLE IF NOT EXISTS public.stock_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  change_amount INTEGER NOT NULL, -- e.g. +10 (restock) or -2 (sale)
  reason TEXT NOT NULL, -- e.g. 'restock', 'invoice_sale', 'adjustment'
  reference_id TEXT, -- e.g. Invoice ID
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for Stock Ledger
ALTER TABLE stock_ledger ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Team members can manage stock ledger" ON stock_ledger;
CREATE POLICY "Team members can manage stock ledger" ON stock_ledger FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

-- 4. Automated Stock Update Trigger
-- This function ensures that whenever a ledger entry is added, 
-- the 'stock_quantity' in 'products' is updated automatically.
CREATE OR REPLACE FUNCTION update_product_stock()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.products
  SET stock_quantity = stock_quantity + NEW.change_amount
  WHERE id = NEW.product_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_update_stock_on_ledger ON public.stock_ledger;
CREATE TRIGGER tr_update_stock_on_ledger
AFTER INSERT ON public.stock_ledger
FOR EACH ROW EXECUTE FUNCTION update_product_stock();


-- Seed initial categories for convenience
-- (Note: user_id must be provided, skipping seed to avoid constraint issues)
