-- ============================================================
-- NobleInvoice: Team Support & RBAC Migration
-- ============================================================

-- 1. Create Team Roles Enum
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'team_role') THEN
        CREATE TYPE public.team_role AS ENUM ('owner', 'admin', 'staff', 'accountant');
    END IF;
END $$;

-- 2. Teams Table
CREATE TABLE IF NOT EXISTS public.teams (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Team Members Table (Roles)
CREATE TABLE IF NOT EXISTS public.team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  role team_role NOT NULL DEFAULT 'staff',
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(team_id, user_id)
);

-- 4. Update Existing Tables with team_id
DO $$
BEGIN
    -- Folders
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='folders') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='folders' AND column_name='team_id') THEN
        ALTER TABLE public.folders ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Clients
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='clients') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='team_id') THEN
        ALTER TABLE public.clients ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Invoices
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='invoices') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='invoices' AND column_name='team_id') THEN
        ALTER TABLE public.invoices ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Expenses
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='expenses') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='expenses' AND column_name='team_id') THEN
        ALTER TABLE public.expenses ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Vendors
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='vendors') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendors' AND column_name='team_id') THEN
        ALTER TABLE public.vendors ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Products
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='products') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='team_id') THEN
        ALTER TABLE public.products ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Product Categories
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='product_categories') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='product_categories' AND column_name='team_id') THEN
        ALTER TABLE public.product_categories ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;

    -- Stock Ledger
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='stock_ledger') AND 
       NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='stock_ledger' AND column_name='team_id') THEN
        ALTER TABLE public.stock_ledger ADD COLUMN team_id UUID REFERENCES public.teams(id);
    END IF;
END $$;

-- 5. Data Migration: Create "Personal Teams" for existing users
-- Ensure each profile has at least one team, and migrate their current data to it.
DO $$
DECLARE
    p_record RECORD;
    new_team_id UUID;
BEGIN
    FOR p_record IN SELECT id, display_name FROM public.profiles LOOP
        -- Check if user already owns a team
        SELECT id INTO new_team_id FROM public.teams WHERE owner_id = p_record.id LIMIT 1;
        
        IF new_team_id IS NULL THEN
            -- Create team
            INSERT INTO public.teams (owner_id, name)
            VALUES (p_record.id, COALESCE(p_record.display_name, 'Personal Team'))
            RETURNING id INTO new_team_id;

            -- Add owner to team_members
            INSERT INTO public.team_members (team_id, user_id, role)
            VALUES (new_team_id, p_record.id, 'owner');
        END IF;

        -- Update existing data to point to this team
        UPDATE public.folders SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
        UPDATE public.clients SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
        UPDATE public.invoices SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
        UPDATE public.expenses SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
        UPDATE public.vendors SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
        UPDATE public.products SET team_id = new_team_id WHERE user_id = p_record.id AND team_id IS NULL;
    END LOOP;
END $$;

-- 6. Helper function to check team membership and role
CREATE OR REPLACE FUNCTION public.check_team_access(t_id UUID, required_roles team_role[] DEFAULT ARRAY['owner', 'admin', 'staff', 'accountant']::team_role[])
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.team_members 
    WHERE team_id = t_id 
    AND user_id = auth.uid() 
    AND role = ANY(required_roles)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Apply Team-Based RLS to Tables

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their teams" ON teams;
CREATE POLICY "Users can view their teams" ON teams FOR SELECT USING (check_team_access(id));

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view team members" ON team_members;
CREATE POLICY "Users can view team members" ON team_members FOR SELECT USING (check_team_access(team_id));

-- Update all object policies to use check_team_access
DROP POLICY IF EXISTS "Team members can manage folders" ON folders;
CREATE POLICY "Team members can manage folders" ON folders FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

DROP POLICY IF EXISTS "Team members can manage clients" ON clients;
CREATE POLICY "Team members can manage clients" ON clients FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

DROP POLICY IF EXISTS "Team members can manage invoices" ON invoices;
CREATE POLICY "Team members can manage invoices" ON invoices FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

DROP POLICY IF EXISTS "Team members can manage expenses" ON expenses;
CREATE POLICY "Team members can manage expenses" ON expenses FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff', 'accountant']::team_role[]));

DROP POLICY IF EXISTS "Team members can manage products" ON products;
CREATE POLICY "Team members can manage products" ON products FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));

DROP POLICY IF EXISTS "Team members can manage stock ledger" ON stock_ledger;
CREATE POLICY "Team members can manage stock ledger" ON stock_ledger FOR ALL USING (check_team_access(team_id, ARRAY['owner', 'admin', 'staff']::team_role[]));
