import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';

export const metadata: Metadata = {
    title: 'Best AI Invoice Generator Free — Create Invoices in Seconds | NobleInvoice',
    description: 'The best AI invoice generator free online. Turn notes, PDFs, or voice into professional invoices instantly. Export AI invoice generator PDF. Try free — no card needed.',
    keywords: [
        'ai invoice generator',
        'ai invoice generator free',
        'best ai invoice generator',
        'ai invoice generator online',
        'best AI invoice generator free',
        'ai invoice generator pdf',
        'NobleInvoice',
    ],
    openGraph: {
        title: 'Best AI Invoice Generator Free — Create Invoices in Seconds | NobleInvoice',
        description: 'The best AI invoice generator free online. Turn notes, PDFs, or voice into professional invoices in seconds.',
        images: ['/images/hero-dashboard-actual.png'],
    },
    alternates: { canonical: 'https://nobleinvoice.com/features/ai-invoice-generator' },
};

// ── Schema Markup ────────────────────────────────────────────────────────────
const schemaMarkup = [
    {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "name": "NobleInvoice AI Invoice Generator",
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "Web, iOS, Android",
        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
        "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.9", "reviewCount": "5000" },
        "featureList": "AI Invoice Generator Free, AI Invoice Generator PDF, Best AI Invoice Generator Online",
    },
    {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "NobleInvoice",
        "url": "https://nobleinvoice.com",
        "sameAs": ["https://twitter.com/nobleinvoice", "https://linkedin.com/company/nobleinvoice"],
    },
    {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://nobleinvoice.com" },
            { "@type": "ListItem", "position": 2, "name": "Features", "item": "https://nobleinvoice.com/features" },
            { "@type": "ListItem", "position": 3, "name": "AI Invoice Generator", "item": "https://nobleinvoice.com/features/ai-invoice-generator" },
        ],
    },
    {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            { "@type": "Question", "name": "Is the AI invoice generator free?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. NobleInvoice's AI invoice generator free plan lets you create and export up to 10 invoices per month at zero cost. No credit card required." } },
            { "@type": "Question", "name": "Can I download my invoice as a PDF?", "acceptedAnswer": { "@type": "Answer", "text": "Absolutely. Every invoice generated by our AI invoice generator PDF engine is instantly downloadable as a professionally formatted PDF." } },
            { "@type": "Question", "name": "How does the AI know what to put on the invoice?", "acceptedAnswer": { "@type": "Answer", "text": "You simply type a note, paste project details, or upload a receipt. Our NLP engine identifies client details, line items, tax rates, and due dates automatically." } },
            { "@type": "Question", "name": "Is NobleInvoice the best AI invoice generator online?", "acceptedAnswer": { "@type": "Answer", "text": "NobleInvoice is built for businesses and freelancers who want more than a template. With predictive cash flow, embedded payment links, and 99.8% OCR accuracy, it goes beyond what most AI invoice tools offer." } },
            { "@type": "Question", "name": "Can I accept online payments from the invoice?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Every invoice includes an embedded payment link powered by Flutterwave, supporting card, bank transfer, Apple Pay, Google Pay, and 135+ currencies." } },
            { "@type": "Question", "name": "Is my data secure?", "acceptedAnswer": { "@type": "Answer", "text": "All data is encrypted in transit and at rest. We are SOC 2 Type II certified and fully NDPA/GDPR aligned. We never store raw audio or unprocessed documents." } },
            { "@type": "Question", "name": "Does it work on mobile?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Our best AI invoice generator free mobile experience works on any device. You can dictate, type, or upload from iPhone or Android." } },
        ],
    },
];

// ── Feature Checklist ───────────────────────────────────────────────────────
const features = [
    'AI Invoice Generator (text-to-invoice)',
    'AI Invoice Generator PDF export',
    'OCR Receipt-to-Invoice Matching',
    'Predictive Cash Flow Modeling',
    'Automated payment reminders',
    'Embedded Flutterwave payment links',
    'QR code instant checkout',
    'Real-time invoice open tracking',
    '180+ professional branded templates',
    'Multi-currency support (135+ currencies)',
    'Client & contact management',
    'Recurring invoice scheduling',
    'Estimates-to-invoice conversion',
    'Expense manager & receipt scanner',
    'AI assistant for financial queries',
    'Role-based team workspace',
];

// ── Reviews (with images) ────────────────────────────────────────────────────
const reviews = [
    {
        quote: "I used to spend my Sunday evenings organizing bills. I switched to NobleInvoice, set up automated recurring profiles, and bought my weekends back.",
        name: "Sarah T.",
        role: "Design Agency Founder",
        image: "/images/reviews/ayasha-khan-marketing-director-of-noblemart-marketplace-us-region.png",
    },
    {
        quote: "Tracking media production expenses used to be a nightmare. The Smart Expense Manager categorizes everything automatically across our team, saving us hours each week.",
        name: "Beautrice Moreau",
        role: "Operations Manager, Eagles Media",
        image: "/images/reviews/beautrice-moreau-operations-manager-at-eagles-media.png",
    },
    {
        quote: "The precision of the invoice templates and automated payment collection gives our fintech startup the enterprise-grade look we need to build trust with investors.",
        name: "Kenneth Matthew",
        role: "CEO, FundMe Naija",
        image: "/images/reviews/kenneth-matthew-ceo-of-fundme-naija.jpeg",
    },
];

export default function AIInvoiceGeneratorPage() {
    return (
        <div className="bg-gradient-to-b from-[#F0F9FF] via-white to-[#F5FCFF] text-near-black font-inter antialiased overflow-x-hidden pt-[118px]">
            {schemaMarkup.map((schema, i) => (
                <script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
            ))}

            {/* ── 1. HERO ──────────────────────────────────────────────────── */}
            <section className="relative min-h-[90vh] flex items-center pt-12 pb-24 overflow-hidden">
                <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-noble-blue/5 blur-[120px] rounded-full -translate-y-1/2 translate-x-1/2 pointer-events-none" />
                <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-electric-cyan/5 blur-[100px] rounded-full translate-y-1/2 -translate-x-1/2 pointer-events-none" />

                <div className="max-w-[1430px] mx-auto px-4 md:px-16 w-full grid lg:grid-cols-[1.1fr_0.9fr] gap-16 items-center">
                    <div className="relative z-10">
                        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white text-noble-blue font-bold text-[10px] md:text-xs uppercase tracking-widest mb-8 border border-near-black/5 shadow-sm">
                            <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                            Best AI Invoice Generator Online — Free to Start
                        </div>

                        <h1 className="font-inter text-near-black mb-6 text-[30px] md:text-[50px] leading-[1.05] tracking-tight font-black" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                            Stop Typing Invoices. Let <span className="text-noble-blue">AI Do It</span> in Seconds.
                        </h1>

                        <p className="text-lg md:text-xl text-near-black/60 max-w-xl mb-10 leading-relaxed font-medium">
                            The best AI invoice generator free for freelancers, agencies, and growing businesses. Drop a note, a PDF receipt, or type a quick description — and get a polished, tax-compliant invoice ready to send and get paid.
                        </p>

                        <div className="flex flex-col sm:flex-row gap-4 mb-6">
                            <Link
                                href="/register"
                                id="hero-cta-register"
                                className="text-white px-10 py-5 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all flex items-center justify-center gap-3 shadow-[0_20px_50px_rgba(22,111,187,0.3)] hover:scale-[1.02] active:scale-95"
                                style={{ backgroundColor: '#166FBB' }}
                            >
                                Start Generating Free
                                <span className="material-symbols-outlined">arrow_forward</span>
                            </Link>
                            <Link
                                href="/pricing"
                                id="hero-cta-pricing"
                                className="flex items-center justify-center gap-3 px-8 py-5 text-base font-bold rounded-2xl border-2 border-near-black/10 text-near-black hover:border-noble-blue hover:text-noble-blue hover:bg-noble-blue/5 transition-all"
                            >
                                View Pricing
                            </Link>
                        </div>

                        <p className="text-[11px] text-near-black/35 font-bold uppercase tracking-widest mb-10">
                            No credit card required · Free AI invoice generator PDF · Cancel anytime
                        </p>

                        {/* Social Proof Avatars */}
                        <div className="flex items-center gap-4 border-t border-near-black/5 pt-8">
                            <div className="flex -space-x-3">
                                {[
                                    { img: '/images/reviews/ayasha-khan-marketing-director-of-noblemart-marketplace-us-region.png', name: 'Ayasha' },
                                    { img: '/images/reviews/beautrice-moreau-operations-manager-at-eagles-media.png', name: 'Beautrice' },
                                    { img: '/images/reviews/kenneth-matthew-ceo-of-fundme-naija.jpeg', name: 'Kenneth' },
                                ].map((a, i) => (
                                    <div key={i} className="w-9 h-9 rounded-full border-2 border-white overflow-hidden shadow-sm">
                                        <Image src={a.img} alt={a.name} width={36} height={36} className="w-full h-full object-cover" />
                                    </div>
                                ))}
                            </div>
                            <div>
                                <div className="flex gap-0.5 mb-0.5 text-yellow-400 text-xs">★★★★★</div>
                                <p className="text-[11px] font-bold text-near-black/50">
                                    Trusted by <span className="text-near-black font-black">growing</span> businesses globally
                                </p>
                            </div>
                            {/* Third-party trust */}
                            <div className="hidden md:flex items-center gap-3 ml-4 pl-4 border-l border-near-black/8">
                                <div className="flex items-center gap-1.5">
                                    <span className="material-symbols-outlined text-green-500 text-base">verified_user</span>
                                    <span className="text-[10px] font-black text-near-black/60 uppercase tracking-tight">SOC 2 II</span>
                                </div>
                                <div className="w-px h-5 bg-near-black/8" />
                                <div className="flex items-center gap-1">
                                    <div className="w-5 h-5 rounded bg-[#FF492C] flex items-center justify-center text-white font-black text-[8px]">G2</div>
                                    <span className="text-yellow-400 text-xs">★</span>
                                    <span className="text-[10px] font-bold text-near-black/50">4.9</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Hero Visual */}
                    <div className="relative flex justify-center items-center lg:pl-10" style={{ perspective: '1200px' }}>
                        <div
                            className="relative w-full bg-white/50 backdrop-blur-sm p-3 sm:p-4 rounded-[24px] sm:rounded-[40px] shadow-[0_50px_100px_rgba(0,0,0,0.15)] border border-white/80 overflow-hidden"
                            style={{ transform: 'rotateY(-8deg) rotateX(3deg)' }}
                        >
                            <div className="flex items-center gap-1.5 px-2 pb-3 pt-1">
                                <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                                <div className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                                <div className="w-2.5 h-2.5 rounded-full bg-green-400" />
                            </div>
                            <div className="rounded-[16px] sm:rounded-[32px] overflow-hidden border border-slate-100/50 shadow-inner bg-slate-50 aspect-video flex items-center justify-center relative">
                                <Image
                                    src="/images/features/ai-invoice-generator-demo.png"
                                    alt="NobleInvoice AI generating an invoice from a typed note in real-time"
                                    fill
                                    className="object-cover"
                                />
                            </div>
                        </div>
                        {/* Floating badge */}
                        <div className="absolute -bottom-4 -left-4 lg:-left-8 bg-white rounded-2xl px-5 py-3.5 shadow-[0_20px_60px_rgba(0,0,0,0.12)] border border-near-black/5 z-20 flex items-center gap-3">
                            <div className="w-9 h-9 rounded-xl bg-green-500/10 flex items-center justify-center shrink-0">
                                <span className="material-symbols-outlined text-green-500 text-base">check_circle</span>
                            </div>
                            <div>
                                <p className="text-[10px] font-black text-near-black uppercase tracking-wider">Invoice Paid</p>
                                <p className="text-base font-black text-green-700">+$4,500.00</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ── 2. PARTNER TRUST STRIP ───────────────────────────────────── */}
            <section className="py-10 bg-white border-y border-slate-100">
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 flex flex-wrap items-center justify-center gap-8 text-near-black/30 font-black text-xs uppercase tracking-widest">
                    <span>Flutterwave Partner</span>
                    <span className="w-1 h-1 rounded-full bg-near-black/20" />
                    <span>SOC 2 Type II Certified</span>
                    <span className="w-1 h-1 rounded-full bg-near-black/20" />
                    <span>NDPA Compliant</span>
                    <span className="w-1 h-1 rounded-full bg-near-black/20" />
                    <span>135+ Currencies Supported</span>
                    <span className="w-1 h-1 rounded-full bg-near-black/20" />
                    <span>4.9 ★ G2 Reviews</span>
                </div>
            </section>

            {/* ── 3. PROBLEM SECTION ───────────────────────────────────────── */}
            <section className="py-24 md:py-32 relative overflow-hidden bg-white">
                <div className="absolute top-20 left-0 w-[500px] h-[500px] bg-red-500/[0.03] blur-[120px] rounded-full -translate-x-1/3 pointer-events-none" />
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 relative z-10">
                    <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-center">
                        <div>
                            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-red-500/8 border border-red-500/10 text-red-600 font-bold text-[10px] uppercase tracking-widest mb-6">
                                <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
                                Why Most Businesses Fail at Invoicing
                            </div>
                            <h2 className="font-inter text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] mb-6 tracking-tight" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                                Manual billing is <span className="text-red-500/80">quietly killing</span> your cash flow.
                            </h2>
                            <div className="text-base md:text-lg text-near-black/60 space-y-5 leading-relaxed font-medium">
                                <p>You finish a project. Then instead of moving on, you sit down to build an invoice from scratch in Word or Excel — trying to remember what you quoted, whether you applied VAT, and what your client's bank details were.</p>
                                <p>That 45-minute process happens every single time. Multiply it by every invoice. That's a real cost — and a real delay before money hits your account.</p>
                                <p>The average freelancer loses <strong className="text-near-black">3+ hours a week</strong> just formatting invoices. The average B2B business waits <strong className="text-near-black">14 days longer</strong> when using static templates. Our best AI invoice generator free tool eliminates both.</p>
                            </div>
                        </div>

                        <div className="space-y-4">
                            {[
                                { icon: 'schedule', label: 'Manual data entry errors', stat: '#1 cause of delayed client payments', color: 'red' },
                                { icon: 'hourglass_top', label: 'The 14-day cash flow gap', stat: 'Avg. wait when using Word / Excel templates', color: 'red' },
                                { icon: 'sentiment_dissatisfied', label: 'Lost billable hours', stat: '3+ hours/week spent formatting, not billing', color: 'red' },
                            ].map((point, idx) => (
                                <div key={idx} className="group bg-slate-50 rounded-[24px] p-6 md:p-8 border border-slate-100 shadow-sm hover:shadow-xl hover:border-red-500/10 transition-all duration-500">
                                    <div className="flex items-center gap-5">
                                        <div className="w-14 h-14 rounded-2xl bg-red-500/8 flex items-center justify-center shrink-0 group-hover:bg-red-500 transition-colors duration-300">
                                            <span className="material-symbols-outlined text-red-500 group-hover:text-white text-2xl">{point.icon}</span>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h3 className="font-black text-near-black text-xl mb-1">{point.label}</h3>
                                            <p className="text-near-black/40 text-sm font-bold">{point.stat}</p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                            <div className="bg-gradient-to-r from-red-500/5 to-transparent rounded-2xl p-5 border-l-4 border-red-500/30 mt-2">
                                <p className="text-sm text-near-black/50 font-medium leading-relaxed">
                                    <strong className="text-near-black/70">The hidden cost?</strong> It's not just time. It's the projects you could have taken while you were stuck doing admin. An AI invoice generator online handles all of this so you don't have to.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* ── 4. APPROACH + INFORMATION GAIN ──────────────────────────── */}
            <section className="py-24 md:py-32 bg-[#F8FAFC]">
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 text-center mb-16">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-6">
                        The NobleInvoice Framework
                    </div>
                    <h2 className="text-4xl md:text-5xl lg:text-6xl font-black text-near-black leading-[1.1] mb-6 tracking-tight" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                        Beyond templates. This is an <span className="text-noble-blue">intelligent billing engine.</span>
                    </h2>
                    <p className="text-lg text-near-black/60 max-w-2xl mx-auto font-medium">
                        Most tools just give you a form with fields to fill. Our AI invoice generator online understands context, learns from your billing patterns, and predicts what happens next.
                    </p>
                </div>

                <div className="max-w-[1430px] mx-auto px-4 md:px-16 grid md:grid-cols-2 gap-8">
                    {/* IG 1 */}
                    <div className="bg-white rounded-[32px] p-8 md:p-12 border border-slate-100 shadow-sm hover:shadow-xl hover:border-noble-blue/20 transition-all">
                        <div className="w-12 h-12 bg-noble-blue/10 rounded-xl flex items-center justify-center mb-6">
                            <span className="material-symbols-outlined text-noble-blue text-2xl">document_scanner</span>
                        </div>
                        <h3 className="text-3xl font-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>OCR-to-Invoice Contextual Matching</h3>
                        <p className="text-near-black/60 leading-relaxed font-medium mb-4">
                            Generic OCR tools read text. Our AI invoice generator pdf engine <em>understands meaning</em>. Drop a crumpled receipt and it distinguishes a tip from a regional tax from a base service fee — with 99.8% extraction accuracy.
                        </p>
                        <p className="text-near-black/60 leading-relaxed font-medium mb-6">
                            Competitors use character-level extraction that breaks when formatting is inconsistent. We use contextual pattern recognition trained on millions of invoice structures.
                        </p>
                        <div className="aspect-video bg-slate-50 rounded-2xl flex items-center justify-center border border-slate-200 relative overflow-hidden">
                            <Image src="/images/features/ocr_accuracy_chart.png" alt="OCR accuracy comparison chart - NobleInvoice 99.8% vs. industry avg 92%" fill className="object-cover" />
                        </div>
                    </div>

                    {/* IG 2 */}
                    <div className="bg-white rounded-[32px] p-8 md:p-12 border border-slate-100 shadow-sm hover:shadow-xl hover:border-noble-blue/20 transition-all">
                        <div className="w-12 h-12 bg-noble-blue/10 rounded-xl flex items-center justify-center mb-6">
                            <span className="material-symbols-outlined text-noble-blue text-2xl">monitoring</span>
                        </div>
                        <h3 className="text-3xl font-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>Predictive Cash Flow Modeling</h3>
                        <p className="text-near-black/60 leading-relaxed font-medium mb-4">
                            Generating the document is step one. Our AI invoice generator online goes further — it analyzes each client's historical payment behavior and flags invoices at risk of being paid late before you even click send.
                        </p>
                        <p className="text-near-black/60 leading-relaxed font-medium mb-6">
                            Know exactly when money will land, not just when the invoice says it's due. Plan your cash flow with real data. No other best AI invoice generator free tool does this.
                        </p>
                        <div className="aspect-video bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl flex items-center justify-center border border-slate-200 overflow-hidden relative shadow-inner">
                            <Image src="/images/cashflow-dashboard.png" alt="Cash flow prediction timeline dashboard" fill className="object-cover" />
                        </div>
                    </div>
                </div>
            </section>

            {/* ── 5. FEATURE CHECKLIST ─────────────────────────────────────── */}
            <section className="py-24 relative overflow-hidden bg-near-black text-white">
                <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-noble-blue/20 blur-[150px] rounded-full translate-x-1/3 -translate-y-1/3 pointer-events-none" />
                <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-electric-cyan/10 blur-[150px] rounded-full -translate-x-1/3 translate-y-1/3 pointer-events-none" />
                
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 relative z-10">
                    <div className="text-center mb-16">
                        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 text-electric-cyan font-bold text-[10px] uppercase tracking-widest mb-6 border border-white/5 shadow-sm">
                            Everything Included
                        </div>
                        <h2 className="text-4xl md:text-5xl lg:text-6xl font-black leading-[1.1] mb-6 tracking-tight" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                            16 tools in one. <span className="text-transparent bg-clip-text bg-gradient-to-r from-electric-cyan to-noble-blue">All free to start.</span>
                        </h2>
                        <p className="text-lg text-white/60 font-medium mb-10 max-w-2xl mx-auto leading-relaxed">
                            The best AI invoice generator free plan gives you immediate access to all the core features below. Upgrade only when you need volume or advanced automation.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6 mb-16">
                        {features.map((f, i) => (
                            <div key={i} className="group relative bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 hover:bg-white/10 hover:border-white/20 hover:-translate-y-1 transition-all duration-300 shadow-xl overflow-hidden">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-electric-cyan/0 to-transparent group-hover:via-electric-cyan/50 transition-all duration-500" />
                                <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300 border border-white/5 shadow-inner">
                                    <span className="material-symbols-outlined text-electric-cyan">check_circle</span>
                                </div>
                                <span className="text-white/90 font-bold text-[15px] leading-snug block">{f}</span>
                            </div>
                        ))}
                    </div>

                    <div className="text-center">
                        <Link
                            href="/register"
                            id="checklist-cta"
                            className="text-near-black px-12 py-5 text-base font-black rounded-2xl hover:opacity-90 transition-all inline-flex items-center justify-center gap-3 hover:scale-[1.02] active:scale-95 bg-white shadow-[0_0_40px_rgba(0,240,255,0.3)]"
                        >
                            Start Free Today
                            <span className="material-symbols-outlined text-near-black">arrow_forward</span>
                        </Link>
                    </div>
                </div>
            </section>

            {/* ── 6. HOW IT WORKS ─────────────────────────────────────────── */}
            <section className="py-24 bg-[#F8FAFC]">
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 text-center">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-noble-blue/10 text-noble-blue font-bold text-[10px] uppercase tracking-widest mb-6">
                        Simple Process
                    </div>
                    <h2 className="text-4xl md:text-5xl font-black text-near-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                        From note to paid invoice in 3 steps
                    </h2>
                    <p className="text-lg text-near-black/60 font-medium mb-16 max-w-2xl mx-auto">
                        This is what makes NobleInvoice the best AI invoice generator online for people who actually have work to do.
                    </p>
                    <div className="grid md:grid-cols-3 gap-8">
                        {[
                            { step: '01', icon: 'edit_note', title: 'Upload, Type, or Speak', desc: 'Drop a PDF receipt, paste your project notes, or type something like "Invoice John for 5 hours consulting at $150/hr." Our AI does the rest.' },
                            { step: '02', icon: 'auto_awesome', title: 'AI Structures It Instantly', desc: 'Line items, taxes, client details, due dates, and your branding — all formatted automatically. AI invoice generator PDF export is ready in seconds.' },
                            { step: '03', icon: 'payments', title: 'Send & Get Paid', desc: 'Send the invoice with an embedded Flutterwave payment link. Clients pay via card, bank transfer, Apple Pay, or Google Pay in 135+ currencies.' },
                        ].map((s, i) => (
                            <div key={i} className="text-left p-8 rounded-3xl bg-white border border-slate-100 hover:shadow-xl hover:border-noble-blue/20 transition-all">
                                <div className="flex items-start justify-between mb-6">
                                    <div className="text-5xl font-black text-noble-blue/15">{s.step}</div>
                                    <div className="w-12 h-12 bg-noble-blue/10 rounded-xl flex items-center justify-center">
                                        <span className="material-symbols-outlined text-noble-blue">{s.icon}</span>
                                    </div>
                                </div>
                                <h4 className="text-xl font-black mb-3" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>{s.title}</h4>
                                <p className="text-near-black/60 font-medium leading-relaxed">{s.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── 7. COMPARISON TABLE ─────────────────────────────────────── */}
            <section className="py-24 bg-white">
                <div className="max-w-5xl mx-auto px-4 md:px-16">
                    <div className="text-center mb-16">
                        <h2 className="text-4xl md:text-5xl font-black text-near-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                            AI Invoice Generator vs. The Old Way
                        </h2>
                        <p className="text-lg text-near-black/60 font-medium">See why businesses worldwide switched from spreadsheets and generic templates.</p>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-slate-200">
                                    <th className="text-left py-4 pr-4 font-black text-near-black/60 text-xs uppercase tracking-widest">Feature</th>
                                    <th className="text-center py-4 px-4 font-black text-noble-blue text-xs uppercase tracking-widest">NobleInvoice</th>
                                    <th className="text-center py-4 px-4 font-black text-near-black/40 text-xs uppercase tracking-widest">Word / Excel</th>
                                    <th className="text-center py-4 px-4 font-black text-near-black/40 text-xs uppercase tracking-widest">Generic AI Tools</th>
                                </tr>
                            </thead>
                            <tbody>
                                {[
                                    ['AI text-to-invoice generation', true, false, true],
                                    ['AI invoice generator PDF export', true, false, true],
                                    ['OCR receipt scanning (99.8% accuracy)', true, false, false],
                                    ['Predictive cash flow modeling', true, false, false],
                                    ['Embedded payment links (Flutterwave)', true, false, false],
                                    ['Real-time invoice open tracking', true, false, false],
                                    ['Automated payment reminders', true, false, false],
                                    ['180+ branded templates', true, true, false],
                                    ['Multi-currency (135+ currencies)', true, false, false],
                                    ['Team collaboration workspace', true, false, false],
                                    ['Free plan available', true, true, true],
                                ].map(([feat, noble, excel, generic], i) => (
                                    <tr key={i} className={`border-b border-slate-100 ${i % 2 === 0 ? 'bg-slate-50/50' : ''}`}>
                                        <td className="py-3.5 pr-4 font-medium text-near-black/80">{feat}</td>
                                        <td className="py-3.5 px-4 text-center">{noble ? <span className="text-green-500 font-black">✓</span> : <span className="text-slate-300">—</span>}</td>
                                        <td className="py-3.5 px-4 text-center">{excel ? <span className="text-slate-400 font-black">✓</span> : <span className="text-slate-300">—</span>}</td>
                                        <td className="py-3.5 px-4 text-center">{generic ? <span className="text-slate-400 font-black">✓</span> : <span className="text-slate-300">—</span>}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>

            {/* ── 8. CASE STUDY / SOCIAL PROOF ─────────────────────────────── */}
            <section className="py-24 bg-noble-blue text-white px-4 md:px-16">
                <div className="max-w-[1430px] mx-auto">
                    <div className="text-center mb-16">
                        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/10 text-white font-bold text-[10px] uppercase tracking-widest mb-4">
                            Real Results
                        </div>
                        <h2 className="text-4xl md:text-5xl font-black text-white leading-[1.1]" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                            What happens when you stop doing it manually
                        </h2>
                    </div>
                    <div className="grid md:grid-cols-3 gap-6">
                        {reviews.map((r, i) => (
                            <div key={i} className="bg-white/10 backdrop-blur-sm rounded-[32px] p-8 border border-white/10">
                                <div className="flex gap-1 mb-6 text-amber-400">★★★★★</div>
                                <blockquote className="text-white/90 font-medium leading-relaxed mb-8 italic">"{r.quote}"</blockquote>
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-white/20 shrink-0">
                                        <Image src={r.image} alt={r.name} width={40} height={40} className="w-full h-full object-cover" />
                                    </div>
                                    <div>
                                        <p className="font-black text-sm text-white">{r.name}</p>
                                        <p className="text-blue-200 text-[11px] font-bold uppercase tracking-wider">{r.role}</p>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── 9. STATS ─────────────────────────────────────────────────── */}
            <section className="py-16 bg-white border-y border-slate-100">
                <div className="max-w-[1430px] mx-auto px-4 md:px-16 grid grid-cols-2 md:grid-cols-4 gap-6">
                    {[
                        { value: '85%', label: 'Less time on invoice drafting' },
                        { value: '40%', label: 'Fewer late payments in 60 days' },
                        { value: '99.8%', label: 'AI extraction accuracy' },
                        { value: 'Global', label: 'Businesses billing with NobleInvoice' },
                    ].map((stat, i) => (
                        <div key={i} className="text-center">
                            <p className="text-3xl md:text-4xl font-black text-noble-blue">{stat.value}</p>
                            <p className="text-xs font-bold text-near-black/40 mt-2 uppercase tracking-wide leading-snug">{stat.label}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* ── 10. PRICING CALLOUT ──────────────────────────────────────── */}
            <section className="py-24 bg-[#F8FAFC]">
                <div className="max-w-5xl mx-auto px-4 md:px-16 text-center mb-12">
                    <h2 className="text-4xl md:text-5xl font-black text-near-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                        Simple, honest pricing
                    </h2>
                    <p className="text-lg text-near-black/60 font-medium">Start free. Upgrade only when you need more. The best AI invoice generator free plan gives you everything to get started.</p>
                </div>
                <div className="max-w-5xl mx-auto px-4 md:px-16 grid md:grid-cols-2 gap-6">
                    <div className="bg-white rounded-[32px] p-8 border border-slate-200">
                        <div className="text-2xl font-black mb-1">Explorer — Free</div>
                        <div className="text-4xl font-black text-noble-blue mb-4">$0 <span className="text-base text-near-black/40 font-bold">/forever</span></div>
                        <ul className="space-y-3 mb-8">
                            {['AI Invoice Generator — 10 invoices/month', 'AI invoice generator PDF export', 'Basic branded templates', 'Online payment links', 'Client management'].map((item, i) => (
                                <li key={i} className="flex items-center gap-3 text-sm text-near-black/70 font-medium">
                                    <span className="material-symbols-outlined text-green-500 text-base">check_circle</span>
                                    {item}
                                </li>
                            ))}
                        </ul>
                        <Link href="/register" id="pricing-free-cta" className="text-white w-full py-4 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all flex items-center justify-center gap-2 shadow-[0_20px_50px_rgba(22,111,187,0.3)]" style={{ backgroundColor: '#166FBB' }}>
                            Start Free Today
                        </Link>
                    </div>
                    <div className="bg-near-black rounded-[32px] p-8 border border-near-black text-white">
                        <div className="text-2xl font-black mb-1">Pro — Best Value</div>
                        <div className="text-4xl font-black text-noble-blue mb-4">From $9.99 <span className="text-base text-white/40 font-bold">/month</span></div>
                        <ul className="space-y-3 mb-8">
                            {['Unlimited AI invoices & estimates', 'Predictive cash flow modeling', 'Automated payment reminders', 'OCR receipt scanning', 'Team workspace (5 seats)', 'Priority support'].map((item, i) => (
                                <li key={i} className="flex items-center gap-3 text-sm text-white/70 font-medium">
                                    <span className="material-symbols-outlined text-green-400 text-base">check_circle</span>
                                    {item}
                                </li>
                            ))}
                        </ul>
                        <Link href="/pricing" id="pricing-pro-cta" className="bg-noble-blue text-white w-full py-4 text-base font-extrabold rounded-2xl hover:opacity-90 transition-all flex items-center justify-center gap-2">
                            See Full Pricing
                        </Link>
                    </div>
                </div>
            </section>

            {/* ── 11. FAQ ──────────────────────────────────────────────────── */}
            <section className="py-24 bg-white px-4 md:px-16">
                <div className="max-w-3xl mx-auto">
                    <div className="text-center mb-16">
                        <h2 className="text-4xl md:text-5xl font-black text-near-black mb-4" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                            Frequently Asked Questions
                        </h2>
                        <p className="text-near-black/60 font-medium">Everything you need to know about our AI invoice generator online.</p>
                    </div>
                    <div className="space-y-4">
                        {[
                            { q: "Is the AI invoice generator free?", a: "Yes. NobleInvoice's AI invoice generator free plan lets you create up to 10 invoices per month at zero cost. No credit card needed to start." },
                            { q: "Can I download my invoice as a PDF?", a: "Every invoice made with our AI invoice generator PDF engine is instantly downloadable. Professional layout, branded, and ready to send." },
                            { q: "How does the AI know what to put on the invoice?", a: "You type a quick note, paste project details, or upload a receipt. Our NLP engine identifies client info, line items, tax rates, and due dates automatically — achieving 99.8% accuracy." },
                            { q: "Is NobleInvoice the best AI invoice generator online?", a: "For businesses that want more than a basic template — yes. Predictive cash flow, embedded payment links, OCR scanning, and real-time tracking set NobleInvoice apart from generic AI invoice tools." },
                            { q: "Can I accept payments directly from the invoice?", a: "Yes. Every invoice includes a Flutterwave-powered payment link. Clients pay via card, bank transfer, Apple Pay, Google Pay, or local methods in 135+ currencies." },
                            { q: "Is my business data secure?", a: "Absolutely. All data is encrypted in transit and at rest. We are SOC 2 Type II certified and fully NDPA/GDPR aligned. We never store raw documents beyond the invoice session." },
                            { q: "Does this work as a free AI invoice generator on mobile?", a: "Yes. The full AI invoice generator online experience works on any device — no app download required. Just open your browser on iPhone or Android and start." },
                        ].map((faq, i) => (
                            <div key={i} className="p-6 rounded-2xl bg-slate-50 border border-slate-100">
                                <h4 className="text-base font-black text-slate-900 mb-2">{faq.q}</h4>
                                <p className="text-slate-600 leading-relaxed font-medium text-sm">{faq.a}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── 12. NOT RIGHT FOR YOU ────────────────────────────────────── */}
            <section className="py-16 bg-[#F8FAFC] border-t border-slate-100 px-4 md:px-16">
                <div className="max-w-3xl mx-auto">
                    <div className="bg-white rounded-[24px] p-8 border border-slate-200">
                        <h3 className="text-xl font-black mb-4 text-near-black">We might not be right for you if…</h3>
                        <div className="text-near-black/60 font-medium space-y-3 leading-relaxed">
                            <p>You just need to print a one-time invoice with no follow-up. A free Word template will do the job.</p>
                            <p>You don't care whether clients open your invoices or pay on time. You prefer to call and chase manually.</p>
                            <p>You have no interest in knowing your cash flow position before it surprises you.</p>
                        </div>
                        <p className="mt-5 text-near-black/80 font-bold">If any of that doesn't sound like you — you're in the right place. NobleInvoice is built for people who treat their business like a business.</p>
                    </div>
                </div>
            </section>

            {/* ── 13. INTERNAL LINKS ───────────────────────────────────────── */}
            <section className="py-16 bg-white px-4 md:px-16">
                <div className="max-w-[1430px] mx-auto">
                    <p className="text-center text-xs font-black text-near-black/30 uppercase tracking-widest mb-8">Explore More NobleInvoice Tools</p>
                    <div className="flex flex-wrap justify-center gap-3">
                        {[
                            { label: 'Free Invoice Maker', href: '/features/how-to-make-an-invoice-for-free' },
                            { label: 'Billing Software Online', href: '/features/billing-software-online' },
                            { label: 'Shopify Invoice Generator', href: '/features/shopify-invoice-generator' },
                            { label: 'Digital Business Cards', href: '/features/digital-business-cards' },
                            { label: 'QR Code Generator', href: '/features/how-to-generate-a-qr-code' },
                            { label: 'Best Free Invoice App', href: '/features/best-free-invoice-app' },
                            { label: 'Pricing Plans', href: '/pricing' },
                            { label: 'Blog & Guides', href: '/blog' },
                        ].map((link, i) => (
                            <Link key={i} href={link.href} className="px-4 py-2 rounded-full text-sm font-bold text-near-black/60 border border-slate-200 hover:border-noble-blue hover:text-noble-blue transition-all">
                                {link.label}
                            </Link>
                        ))}
                    </div>
                </div>
            </section>

            {/* ── 14. BOTTOM CTA ───────────────────────────────────────────── */}
            <section className="py-24 bg-gradient-to-br from-noble-blue to-[#0599D5] px-4 md:px-16 text-center relative overflow-hidden">
                <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 20% 50%, white 1px, transparent 1px), radial-gradient(circle at 80% 50%, white 1px, transparent 1px)', backgroundSize: '60px 60px' }} />
                <div className="max-w-3xl mx-auto space-y-8 relative z-10">
                    <h2 className="text-4xl md:text-5xl lg:text-6xl font-black leading-[1.1] text-white" style={{ fontFamily: 'Clash Display, Syne, Inter, sans-serif' }}>
                        Generate your first AI invoice free — right now.
                    </h2>
                    <p className="text-white/70 text-lg font-medium">Join growing businesses using the best AI invoice generator online to bill smarter and get paid faster.</p>
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                        <Link
                            href="/register"
                            id="bottom-cta-register"
                            className="bg-white text-noble-blue px-10 py-5 text-base font-extrabold rounded-2xl hover:bg-blue-50 transition-all inline-flex items-center justify-center gap-3 shadow-[0_20px_50px_rgba(0,0,0,0.2)] hover:scale-[1.02] active:scale-95"
                        >
                            Start Generating Free
                            <span className="material-symbols-outlined">arrow_forward</span>
                        </Link>
                        <Link
                            href="/pricing"
                            id="bottom-cta-pricing"
                            className="border-2 border-white/40 text-white px-8 py-5 text-base font-bold rounded-2xl hover:bg-white/10 transition-all inline-flex items-center justify-center"
                        >
                            View All Plans
                        </Link>
                    </div>
                    <p className="text-white/40 text-[11px] font-bold uppercase tracking-widest">
                        No credit card required · Free AI invoice generator PDF · Cancel anytime
                    </p>
                </div>
            </section>
        </div>
    );
}
