import { TemplateDefinition } from './templateRegistry';

export const IDENTITY_TEMPLATES: TemplateDefinition[] = [
  { id: 'id-claudia-alves', name: 'Claudia Bakery Artisanal', type: 'identity', category: ['creative'], theme: 'light', accentColor: '#E69138', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-larana-inc', name: 'Larana Vertex Executive', type: 'identity', category: ['executive'], theme: 'light', accentColor: '#D35400', headerStyle: 'diagonal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-chastain-kinetic', name: 'Chastain Navy Kinetic', type: 'identity', category: ['dynamic'], theme: 'dark', accentColor: '#0B2447', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-aldenaire-executive', name: 'Aldenaire Navy Executive', type: 'identity', category: ['executive'], theme: 'light', accentColor: '#0B3D66', headerStyle: 'block', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-wilson-dynamic', name: 'Wilson Dynamic Azure', type: 'identity', category: ['dynamic'], theme: 'light', accentColor: '#00B4DB', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-thynk-azure', name: 'Thynk Azure Dynamic', type: 'identity', category: ['dynamic'], theme: 'light', accentColor: '#0055A4', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-avery-executive', name: 'Avery Executive Portal', type: 'identity', category: ['executive'], theme: 'light', accentColor: '#DC2626', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-gallego-dynamic', name: 'Gallego Dynamic Kinetic', type: 'identity', category: ['dynamic'], theme: 'dark', accentColor: '#10B981', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-liceria-crimson', name: 'Liceria Crimson Elite', type: 'identity', category: ['executive'], theme: 'dark', accentColor: '#A00000', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-rosa-dynamic', name: 'Rosa Maria Dynamic', type: 'identity', category: ['dynamic'], theme: 'light', accentColor: '#00B4DB', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-rosa-crystal', name: 'Rosa Crystal Dynamic', type: 'identity', category: ['dynamic'], theme: 'light', accentColor: '#00B4DB', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-andrade-pro', name: 'Andrade Creative', type: 'identity', category: ['creative'], theme: 'dark', accentColor: '#0055A4', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-borcelle-pro', name: 'Borcelle Executive', type: 'identity', category: ['executive'], theme: 'light', accentColor: '#A00000', headerStyle: 'diagonal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-liceria-liquid', name: 'Liceria Liquid', type: 'identity', category: ['dynamic'], theme: 'dark', accentColor: '#0061FF', headerStyle: 'minimal', footerStyle: 'wave', logoPosition: 'top-right', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-salford-pro', name: 'Salford Dynamic', type: 'identity', category: ['dynamic'], theme: 'dark', accentColor: '#EAB308', headerStyle: 'minimal', footerStyle: 'block', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-kogax-pro', name: 'Kogax Creative', type: 'identity', category: ['creative'], theme: 'dark', accentColor: '#A4D955', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-adeline-pro', name: 'Adeline Executive', type: 'identity', category: ['executive'], theme: 'dark', accentColor: '#EAB308', headerStyle: 'minimal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-ingoude-pro', name: 'Ingoude Executive', type: 'identity', category: ['executive'], theme: 'dark', accentColor: '#9B846F', headerStyle: 'diagonal', footerStyle: 'none', logoPosition: 'center', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-dynamic-wave-pro', name: 'Dynamic Wave', type: 'identity', category: ['dynamic'], theme: 'light', accentColor: '#FF4B6B', headerStyle: 'minimal', footerStyle: 'wave', logoPosition: 'top-right', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-rimberio-pro', name: 'Rimberio Elite', type: 'identity', category: ['executive'], theme: 'dark', accentColor: '#E31E24', headerStyle: 'diagonal', footerStyle: 'none', logoPosition: 'top-left', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' },
  { id: 'id-elite-chevron', name: 'Elite Chevron', type: 'identity', category: ['executive'], theme: 'light', accentColor: '#FCB221', headerStyle: 'diagonal', footerStyle: 'none', logoPosition: 'top-right', orientation: 'horizontal', isPremium: true, thumbnail: '/placeholder.png' }
];
