-- =============================================================================
-- Autonomous SEO Engine Schema Migration
-- Created: 2026-05-26
-- Description: Core tables for keyword clustering, article generation pipeline,
--              SERP rank tracking, and orchestration settings.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. ENUM TYPES
-- ---------------------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE seo_keyword_intent AS ENUM (
    'Informational', 'Transactional', 'Commercial', 'Navigational', 'Local'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE seo_keyword_status AS ENUM (
    'pending', 'processing', 'completed', 'failed'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE seo_article_status AS ENUM (
    'draft', 'published'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ---------------------------------------------------------------------------
-- 2. TABLES
-- ---------------------------------------------------------------------------

-- SEO Keywords: The master keyword registry for the autonomous engine
CREATE TABLE IF NOT EXISTS seo_keywords (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword       TEXT NOT NULL,
  intent        seo_keyword_intent NOT NULL DEFAULT 'Informational',
  volume        INTEGER NOT NULL DEFAULT 0,
  cpc           NUMERIC(8,2) NOT NULL DEFAULT 0.00,
  pd            INTEGER NOT NULL DEFAULT 0,
  seo_difficulty INTEGER NOT NULL DEFAULT 0,
  cluster_parent TEXT,
  status        seo_keyword_status NOT NULL DEFAULT 'pending',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- SEO Articles: Long-form content generated by the autonomous pipeline
CREATE TABLE IF NOT EXISTS seo_articles (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword_id        UUID REFERENCES seo_keywords(id) ON DELETE SET NULL,
  title             TEXT NOT NULL,
  slug              TEXT NOT NULL UNIQUE,
  meta_title        TEXT NOT NULL,
  meta_description  TEXT NOT NULL,
  content_markdown  TEXT NOT NULL DEFAULT '',
  featured_image_url TEXT,
  status            seo_article_status NOT NULL DEFAULT 'draft',
  word_count        INTEGER NOT NULL DEFAULT 0,
  seo_score         NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  human_score       NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  schema_markup     JSONB DEFAULT '{}',
  published_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Rankings Tracker: Historical SERP position snapshots
CREATE TABLE IF NOT EXISTS rankings_tracker (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  keyword_id          UUID NOT NULL REFERENCES seo_keywords(id) ON DELETE CASCADE,
  google_rank         INTEGER NOT NULL DEFAULT 0,
  serps_snapshot_url  TEXT,
  tracked_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- SEO Settings: Global configuration for the autonomous orchestrator
CREATE TABLE IF NOT EXISTS seo_settings (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  default_meta_title      TEXT NOT NULL DEFAULT 'NobleInvoice - Premium Financial Management & CRM Platform',
  default_meta_description TEXT NOT NULL DEFAULT 'Streamline your professional workflow, collect payments rapidly with Flutterwave, and leverage smart client portals.',
  og_defaults             JSONB NOT NULL DEFAULT '{
    "og:type": "website",
    "og:site_name": "NobleInvoice",
    "og:locale": "en_US"
  }',
  auto_publish            BOOLEAN NOT NULL DEFAULT true,
  cron_expression         TEXT NOT NULL DEFAULT '0 8 * * *',
  brand_voice_config      JSONB NOT NULL DEFAULT '{
    "tone": "authoritative-yet-approachable",
    "max_paragraph_lines": 2,
    "pattern_interrupt_interval": [150, 250],
    "banned_words": ["unlock", "leverage", "seamless", "world-class", "cutting-edge", "game-changer", "synergy"],
    "required_sections": ["real_case_study", "practical_framework", "contrarian_insight", "when_not_to_use"],
    "target_word_count": 2500,
    "humanization_pass": true
  }',
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------------
-- 3. PERFORMANCE INDEXES
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_seo_keywords_status ON seo_keywords(status);
CREATE INDEX IF NOT EXISTS idx_seo_keywords_cluster ON seo_keywords(cluster_parent);
CREATE INDEX IF NOT EXISTS idx_seo_keywords_intent ON seo_keywords(intent);
CREATE INDEX IF NOT EXISTS idx_seo_articles_slug ON seo_articles(slug);
CREATE INDEX IF NOT EXISTS idx_seo_articles_status ON seo_articles(status);
CREATE INDEX IF NOT EXISTS idx_seo_articles_keyword_id ON seo_articles(keyword_id);
CREATE INDEX IF NOT EXISTS idx_rankings_keyword_id ON rankings_tracker(keyword_id);
CREATE INDEX IF NOT EXISTS idx_rankings_tracked_at ON rankings_tracker(tracked_at DESC);


-- ---------------------------------------------------------------------------
-- 4. UPDATED_AT TRIGGER AUTOMATION
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_seo_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER seo_keywords_updated_at
    BEFORE UPDATE ON seo_keywords
    FOR EACH ROW
    EXECUTE FUNCTION update_seo_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TRIGGER seo_articles_updated_at
    BEFORE UPDATE ON seo_articles
    FOR EACH ROW
    EXECUTE FUNCTION update_seo_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TRIGGER seo_settings_updated_at
    BEFORE UPDATE ON seo_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_seo_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ---------------------------------------------------------------------------
-- 5. ROW-LEVEL SECURITY (RLS) POLICIES
-- ---------------------------------------------------------------------------

ALTER TABLE seo_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE rankings_tracker ENABLE ROW LEVEL SECURITY;
ALTER TABLE seo_settings ENABLE ROW LEVEL SECURITY;

-- Helper: Check if the current user has a specific admin role
CREATE OR REPLACE FUNCTION has_admin_role(required_role TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid()
    AND role = required_role
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- SEO Keywords Policies
DROP POLICY IF EXISTS "seo_keywords_admin_full" ON seo_keywords;
CREATE POLICY "seo_keywords_admin_full"
  ON seo_keywords FOR ALL
  USING (has_admin_role('super_admin') OR has_admin_role('seo_manager'))
  WITH CHECK (has_admin_role('super_admin') OR has_admin_role('seo_manager'));

DROP POLICY IF EXISTS "seo_keywords_support_read" ON seo_keywords;
CREATE POLICY "seo_keywords_support_read"
  ON seo_keywords FOR SELECT
  USING (has_admin_role('support_staff'));

-- SEO Articles Policies
DROP POLICY IF EXISTS "seo_articles_admin_full" ON seo_articles;
CREATE POLICY "seo_articles_admin_full"
  ON seo_articles FOR ALL
  USING (has_admin_role('super_admin') OR has_admin_role('seo_manager'))
  WITH CHECK (has_admin_role('super_admin') OR has_admin_role('seo_manager'));

DROP POLICY IF EXISTS "seo_articles_support_read" ON seo_articles;
CREATE POLICY "seo_articles_support_read"
  ON seo_articles FOR SELECT
  USING (has_admin_role('support_staff'));

DROP POLICY IF EXISTS "seo_articles_public_published" ON seo_articles;
CREATE POLICY "seo_articles_public_published"
  ON seo_articles FOR SELECT
  USING (status = 'published');

-- Rankings Tracker Policies
DROP POLICY IF EXISTS "rankings_tracker_admin_full" ON rankings_tracker;
CREATE POLICY "rankings_tracker_admin_full"
  ON rankings_tracker FOR ALL
  USING (has_admin_role('super_admin') OR has_admin_role('seo_manager'))
  WITH CHECK (has_admin_role('super_admin') OR has_admin_role('seo_manager'));

DROP POLICY IF EXISTS "rankings_tracker_support_read" ON rankings_tracker;
CREATE POLICY "rankings_tracker_support_read"
  ON rankings_tracker FOR SELECT
  USING (has_admin_role('support_staff'));

-- SEO Settings Policies
DROP POLICY IF EXISTS "seo_settings_admin_full" ON seo_settings;
CREATE POLICY "seo_settings_admin_full"
  ON seo_settings FOR ALL
  USING (has_admin_role('super_admin'))
  WITH CHECK (has_admin_role('super_admin'));

DROP POLICY IF EXISTS "seo_settings_manager_read" ON seo_settings;
CREATE POLICY "seo_settings_manager_read"
  ON seo_settings FOR SELECT
  USING (has_admin_role('seo_manager'));


-- ---------------------------------------------------------------------------
-- 6. SEED DEFAULT SETTINGS ROW
-- ---------------------------------------------------------------------------

INSERT INTO seo_settings (
  default_meta_title,
  default_meta_description,
  auto_publish,
  cron_expression
) 
SELECT
  'NobleInvoice - Premium Financial Management & CRM Platform',
  'Streamline your professional workflow, collect payments rapidly with Flutterwave, and leverage smart client portals.',
  true,
  '0 8 * * *'
WHERE NOT EXISTS (SELECT 1 FROM seo_settings LIMIT 1);
