-- supabase/migrations/20260531020000_add_role_and_audit_logs.sql
--
-- Adds two missing pieces required by the admin panel:
--   1. `role` column on profiles (used for admin access checks).
--   2. `audit_logs` table (used by the admin Audit Log page).
--

-- ── 1. Add `role` column to profiles ─────────────────────────────────────────
-- This column stores the admin role (super_admin, seo_manager, support_staff).
-- Regular users have NULL. This is separate from subscription_tier which
-- tracks the billing plan.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS role TEXT DEFAULT NULL;

COMMENT ON COLUMN public.profiles.role IS
  'Admin role: super_admin, seo_manager, support_staff. '
  'NULL for regular users. Independent of subscription_tier.';

-- ── 2. Create `audit_logs` table ─────────────────────────────────────────────
-- Stores admin actions for compliance and security tracking.

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action      TEXT NOT NULL,
  actor       TEXT NOT NULL,
  resource    TEXT,
  ip          TEXT,
  status      TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'failure')),
  type        TEXT NOT NULL DEFAULT 'system' CHECK (type IN ('security', 'content', 'user', 'system')),
  metadata    JSONB DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
  ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_type
  ON public.audit_logs (type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor
  ON public.audit_logs (actor);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Only superadmins and admin-role users can read audit logs
DROP POLICY IF EXISTS "Admin read audit logs" ON public.audit_logs;
CREATE POLICY "Admin read audit logs" ON public.audit_logs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
       WHERE id = auth.uid()
         AND (is_superadmin = true OR role IN ('super_admin', 'seo_manager', 'support_staff'))
    )
  );

-- Service role can insert audit logs (from Edge Functions)
DROP POLICY IF EXISTS "Service role insert audit logs" ON public.audit_logs;
CREATE POLICY "Service role insert audit logs" ON public.audit_logs
  FOR INSERT
  WITH CHECK (true);

-- Grant access
GRANT SELECT ON TABLE public.audit_logs TO authenticated;
GRANT ALL ON TABLE public.audit_logs TO service_role;
