-- ============================================================
-- NobleInvoice: Identity & Digital Business Card Ecosystem
-- Version: 1.0.0
-- Description: Provisions the schema for identities, leads capture,
--              and telemetry logging.
-- ============================================================

-- 1. IDENTITIES TABLE
CREATE TABLE IF NOT EXISTS public.identities (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    job_title TEXT,
    email TEXT,
    phone TEXT,
    website TEXT,
    card_image_url TEXT,
    design_schema JSONB DEFAULT '{}'::jsonb,
    is_primary BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for lookup optimization
CREATE INDEX IF NOT EXISTS idx_identities_user_id ON public.identities(user_id);
CREATE INDEX IF NOT EXISTS idx_identities_team_id ON public.identities(team_id);

-- Enable RLS
ALTER TABLE public.identities ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Users can manage their own identities" ON public.identities;
CREATE POLICY "Users can manage their own identities" ON public.identities
    FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public can view identities" ON public.identities;
CREATE POLICY "Public can view identities" ON public.identities
    FOR SELECT USING (true); -- Anyone scanning a card can view the profile


-- 2. IDENTITY LEADS TABLE (CRM Leads Capture)
CREATE TABLE IF NOT EXISTS public.identity_leads (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    identity_id UUID REFERENCES public.identities(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_identity_leads_identity_id ON public.identity_leads(identity_id);

-- Enable RLS
ALTER TABLE public.identity_leads ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Identity owners can view their leads" ON public.identity_leads;
CREATE POLICY "Identity owners can view their leads" ON public.identity_leads
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.identities 
            WHERE identities.id = identity_leads.identity_id 
            AND identities.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Public can submit leads" ON public.identity_leads;
CREATE POLICY "Public can submit leads" ON public.identity_leads
    FOR INSERT WITH CHECK (true); -- Public users submit contact form


-- 3. SCAN LOGS TABLE (Analytics Telemetry)
CREATE TABLE IF NOT EXISTS public.scan_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_id UUID REFERENCES public.identities(id) ON DELETE CASCADE NOT NULL,
    scanned_at TIMESTAMPTZ DEFAULT NOW(),
    location TEXT,
    ip_address TEXT,
    user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_scan_logs_identity_id ON public.scan_logs(identity_id);

-- Enable RLS
ALTER TABLE public.scan_logs ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Identity owners can view their scan logs" ON public.scan_logs;
CREATE POLICY "Identity owners can view their scan logs" ON public.scan_logs
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.identities 
            WHERE identities.id = scan_logs.identity_id 
            AND identities.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Public can insert scan logs" ON public.scan_logs;
CREATE POLICY "Public can insert scan logs" ON public.scan_logs
    FOR INSERT WITH CHECK (true); -- Anyone scanning triggers telemetry log
