-- Product Passports Table
CREATE TABLE IF NOT EXISTS public.product_passports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
  hs_code TEXT,
  country_of_origin TEXT,
  brand_name TEXT,
  manufacturer_info JSONB DEFAULT '{}'::jsonb,
  product_images JSONB DEFAULT '[]'::jsonb,
  certifications JSONB DEFAULT '[]'::jsonb,
  batch_number TEXT,
  production_date DATE,
  expiry_date DATE,
  slug TEXT UNIQUE,
  seo_title TEXT,
  seo_description TEXT,
  public_status TEXT DEFAULT 'private',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(product_id)
);

-- Enable RLS
ALTER TABLE public.product_passports ENABLE ROW LEVEL SECURITY;

-- Team Access Policy
DROP POLICY IF EXISTS "Team passport access" ON public.product_passports;
CREATE POLICY "Team passport access" ON public.product_passports 
  FOR ALL USING (check_team_access(team_id));

-- Public Read Policy for Published Passports
DROP POLICY IF EXISTS "Public passport read access" ON public.product_passports;
CREATE POLICY "Public passport read access" ON public.product_passports 
  FOR SELECT USING (public_status = 'published');

-- Trigger for updated_at
DROP TRIGGER IF EXISTS set_product_passports_updated_at ON public.product_passports;
CREATE TRIGGER set_product_passports_updated_at 
  BEFORE UPDATE ON public.product_passports 
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- Analytics Table for Product Scans
CREATE TABLE IF NOT EXISTS public.product_passport_scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passport_id UUID REFERENCES public.product_passports(id) ON DELETE CASCADE NOT NULL,
  scanned_at TIMESTAMPTZ DEFAULT NOW(),
  location_data JSONB,
  user_agent TEXT,
  ip_address TEXT
);

ALTER TABLE public.product_passport_scans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Team passport scans access" ON public.product_passport_scans;
CREATE POLICY "Team passport scans access" ON public.product_passport_scans 
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.product_passports 
      WHERE id = product_passport_scans.passport_id 
      AND check_team_access(team_id)
    )
  );

-- Function to handle public inserts of scans
DROP POLICY IF EXISTS "Public can insert scans" ON public.product_passport_scans;
CREATE POLICY "Public can insert scans" ON public.product_passport_scans
  FOR INSERT WITH CHECK (true);
