import React from 'react';
import Link from 'next/link';
import { Bot, AlertTriangle, ShieldAlert, ArrowLeft } from 'lucide-react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Transparency Disclaimer — NobleInvoice AI Invoice Generator',
  description: 'How NobleInvoice uses AI in our invoice generator. Full transparency on AI-powered features, data processing, and our commitment to responsible AI in billing software.',
  keywords: ['AI invoicing', 'artificial intelligence disclaimer', 'automated billing', 'AI invoice generator'],
};

export default function AIDisclaimerPage() {
    return (
        <div className="min-h-screen bg-black/95 bg-[url('/img/grid.svg')] bg-center bg-fixed text-white py-12 px-6">
            <div className="max-w-3xl mx-auto glass-card p-8 md:p-12 rounded-[2.5rem] border border-white/10 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-96 h-96 bg-[#006970]/10 blur-[100px] rounded-full pointer-events-none" />
                
                <Link href="/" className="inline-flex items-center gap-2 text-xs font-black uppercase text-slate-500 hover:text-white transition-colors mb-8">
                    <ArrowLeft className="w-4 h-4" /> Return Home
                </Link>

                <div className="flex items-center gap-4 mb-8">
                    <div className="p-4 bg-[#006970]/10 rounded-2xl border border-[#006970]/20">
                        <Bot className="w-8 h-8 text-[#006970]" />
                    </div>
                    <div>
                        <h1 className="text-3xl font-black tracking-tight">AI & Cognitive Disclaimer</h1>
                        <p className="text-sm text-slate-400 mt-1 font-medium tracking-wide">Last Updated: March 2026</p>
                    </div>
                </div>

                <div className="space-y-8 text-slate-300 leading-relaxed text-sm md:text-base selection:bg-[#006970]/30">
                    <p className="text-lg font-medium text-white p-6 bg-white/5 rounded-2xl border-l-4 border-l-indigo-500">
                        NobleInvoice utilizes advanced Large Language Models and proprietary sequencing algorithms to synthesize Mind Maps, parse task notes, and schedule Focus blocks.
                    </p>

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold text-white flex items-center gap-2">
                            <AlertTriangle className="w-5 h-5 text-amber-500" /> 1. Accuracy & Hallucinations
                        </h2>
                        <p>
                            The AI generation tools provided (such as the "AI Extend" Mind Map feature and deep-research summarizations) are designed to augment your productivity. However, AI models can produce inaccurate, incomplete, or biased information commonly referred to as "hallucinations." 
                        </p>
                        <p>
                            You should independently verify critical factual data generated by the Cognitive Engine before relying on it for professional, academic, or high-stakes execution.
                        </p>
                    </section>
                    
                    <section className="space-y-4 mt-8">
                        <h2 className="text-xl font-bold text-white flex items-center gap-2">
                            <ShieldAlert className="w-5 h-5 text-[#006970]" /> 2. No Professional Advice
                        </h2>
                        <p>
                            NobleInvoice's "Biological Prime Time" schedule optimization and Mastery path suggestions are productivity frameworks. They do not constitute medical, psychological, or professional health advice. If you are experiencing cognitive fatigue or burnout, please consult a healthcare professional.
                        </p>
                    </section>

                    <section className="space-y-4 mt-8">
                        <h2 className="text-xl font-bold text-white">3. Data Usage Boundaries</h2>
                        <p>
                            We do not use your private, explicit Mind Map node titles or proprietary task descriptions to train our base foundation models. The <i>structural telemetry</i> (how often you complete tasks, session lengths, etc.) is used to refine the scheduling algorithms unless you opt out via your System Preferences.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}

